23:29:44,409 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:44,446 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:44,456 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:44,463 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-25 to job manager
23:29:44,528 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:44,528 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:44,529 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:45,646 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:45,665 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:45,675 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:45,675 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,905 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (13/20)
23:30:18,907 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (13/20)
23:30:21,135 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (104/160)
23:30:21,135 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (104/160)
23:30:21,137 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (104/160)
23:30:21,139 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (104/160)
23:30:22,534 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (103/160)
23:30:22,534 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (103/160)
23:30:22,536 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (103/160)
23:30:22,537 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (103/160)
23:30:22,563 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (100/160)
23:30:22,563 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (100/160)
23:30:22,565 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (100/160)
23:30:22,566 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (100/160)
23:30:22,995 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (99/160)
23:30:22,995 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (99/160)
23:30:22,997 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (99/160)
23:30:22,997 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (99/160)
23:30:23,967 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (97/160)
23:30:23,967 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (97/160)
23:30:23,969 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (97/160)
23:30:23,970 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (97/160)
23:30:24,276 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (101/160)
23:30:24,277 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (101/160)
23:30:24,278 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (101/160)
23:30:24,279 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (101/160)
23:30:24,600 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (98/160)
23:30:24,600 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (98/160)
23:30:24,602 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (98/160)
23:30:24,603 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (98/160)
23:30:25,096 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (102/160)
23:30:25,097 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (102/160)
23:30:25,098 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (102/160)
23:30:25,099 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (102/160)
23:30:56,664 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (13/20)
23:30:56,664 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (13/20)
23:34:43,282 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3120444825232569644_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60744 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:43,282 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3120444825232569644_1565 bad datanode[0] 130.149.21.29:45020
23:34:43,283 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3120444825232569644_1565 in pipeline 130.149.21.29:45020, 130.149.21.17:45020, 130.149.21.18:45020: bad datanode 130.149.21.29:45020
23:34:46,238 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6654573419819278638_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60750 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:46,239 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6654573419819278638_1565 bad datanode[0] 130.149.21.29:45020
23:34:46,240 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6654573419819278638_1565 in pipeline 130.149.21.29:45020, 130.149.21.24:45020, 130.149.21.23:45020: bad datanode 130.149.21.29:45020
23:34:49,297 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8838785834279472899_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60752 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:49,298 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8838785834279472899_1565 bad datanode[0] 130.149.21.29:45020
23:34:49,299 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8838785834279472899_1565 in pipeline 130.149.21.29:45020, 130.149.21.26:45020, 130.149.21.22:45020: bad datanode 130.149.21.29:45020
23:34:57,983 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2355239625853894853_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60757 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:57,983 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2355239625853894853_1565 bad datanode[0] 130.149.21.29:45020
23:34:57,984 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2355239625853894853_1565 in pipeline 130.149.21.29:45020, 130.149.21.61:45020, 130.149.21.30:45020: bad datanode 130.149.21.29:45020
23:35:00,422 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6478818831001085362_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60766 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:00,423 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6478818831001085362_1565 bad datanode[0] 130.149.21.29:45020
23:35:00,424 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6478818831001085362_1565 in pipeline 130.149.21.29:45020, 130.149.21.26:45020, 130.149.21.22:45020: bad datanode 130.149.21.29:45020
23:35:02,175 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8477260620332956752_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60764 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:02,177 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8477260620332956752_1565 bad datanode[0] 130.149.21.29:45020
23:35:02,177 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8477260620332956752_1565 in pipeline 130.149.21.29:45020, 130.149.21.20:45020, 130.149.21.16:45020: bad datanode 130.149.21.29:45020
23:35:06,864 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6276966946539093576_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60759 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:06,865 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6276966946539093576_1565 bad datanode[0] 130.149.21.29:45020
23:35:06,866 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6276966946539093576_1565 in pipeline 130.149.21.29:45020, 130.149.21.28:45020, 130.149.21.21:45020: bad datanode 130.149.21.29:45020
23:35:08,402 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-848093027948157362_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60747 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:08,403 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-848093027948157362_1565 bad datanode[0] 130.149.21.29:45020
23:35:08,403 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-848093027948157362_1565 in pipeline 130.149.21.29:45020, 130.149.21.20:45020, 130.149.21.16:45020: bad datanode 130.149.21.29:45020
23:35:55,394 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8838785834279472899_1593java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:55753 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:55,395 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8838785834279472899_1593 bad datanode[0] 130.149.21.26:45020
23:35:55,396 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8838785834279472899_1593 in pipeline 130.149.21.26:45020, 130.149.21.22:45020: bad datanode 130.149.21.26:45020
23:36:04,060 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2355239625853894853_1609java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:55087 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:04,061 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2355239625853894853_1609 bad datanode[0] 130.149.21.61:45020
23:36:04,062 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2355239625853894853_1609 in pipeline 130.149.21.61:45020, 130.149.21.30:45020: bad datanode 130.149.21.61:45020
23:36:06,520 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6478818831001085362_1618java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:55758 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:06,520 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6478818831001085362_1618 bad datanode[0] 130.149.21.26:45020
23:36:06,521 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6478818831001085362_1618 in pipeline 130.149.21.26:45020, 130.149.21.22:45020: bad datanode 130.149.21.26:45020
23:36:08,218 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8477260620332956752_1629java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:41890 remote=/130.149.21.20:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:08,220 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8477260620332956752_1629 bad datanode[0] 130.149.21.20:45020
23:36:08,220 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8477260620332956752_1629 in pipeline 130.149.21.20:45020, 130.149.21.16:45020: bad datanode 130.149.21.20:45020
23:36:12,964 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6276966946539093576_1653java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:40851 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:12,966 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6276966946539093576_1653 bad datanode[0] 130.149.21.28:45020
23:36:12,966 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6276966946539093576_1653 in pipeline 130.149.21.28:45020, 130.149.21.21:45020: bad datanode 130.149.21.28:45020
23:36:14,480 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-848093027948157362_1661java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:41896 remote=/130.149.21.20:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:14,482 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-848093027948157362_1661 bad datanode[0] 130.149.21.20:45020
23:36:14,482 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-848093027948157362_1661 in pipeline 130.149.21.20:45020, 130.149.21.16:45020: bad datanode 130.149.21.20:45020
23:36:41,866 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3120444825232569644_1568java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:57922 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:41,867 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3120444825232569644_1568 bad datanode[0] 130.149.21.17:45020
23:36:41,868 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3120444825232569644_1568 in pipeline 130.149.21.17:45020, 130.149.21.18:45020: bad datanode 130.149.21.17:45020
