23:29:43,544 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:43,602 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:43,612 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:43,620 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-21 to job manager
23:29:43,685 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:43,685 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:43,686 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:44,804 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:44,824 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:44,833 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:44,834 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,648 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (17/20)
23:30:18,651 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (17/20)
23:30:20,011 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (135/160)
23:30:20,011 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (135/160)
23:30:20,013 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (135/160)
23:30:20,014 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (135/160)
23:30:20,992 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (136/160)
23:30:20,992 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (136/160)
23:30:20,994 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (136/160)
23:30:20,995 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (136/160)
23:30:21,525 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (129/160)
23:30:21,525 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (129/160)
23:30:21,527 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (129/160)
23:30:21,528 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (129/160)
23:30:22,634 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (130/160)
23:30:22,634 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (130/160)
23:30:22,636 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (130/160)
23:30:22,638 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (130/160)
23:30:23,187 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (134/160)
23:30:23,187 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (134/160)
23:30:23,189 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (134/160)
23:30:23,190 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (134/160)
23:30:23,969 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (131/160)
23:30:23,969 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (131/160)
23:30:23,971 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (131/160)
23:30:23,972 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (131/160)
23:30:24,940 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (132/160)
23:30:24,940 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (132/160)
23:30:24,942 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (132/160)
23:30:24,943 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (132/160)
23:30:25,250 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (133/160)
23:30:25,250 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (133/160)
23:30:25,253 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (133/160)
23:30:25,254 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (133/160)
23:31:08,959 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (17/20)
23:31:08,959 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (17/20)
23:35:23,346 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5863880717779162677_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:39385 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:23,347 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5863880717779162677_1565 bad datanode[0] 130.149.21.25:45020
23:35:23,348 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5863880717779162677_1565 in pipeline 130.149.21.25:45020, 130.149.21.27:45020, 130.149.21.23:45020: bad datanode 130.149.21.25:45020
23:35:23,817 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8939771248058631957_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:39400 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:23,818 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8939771248058631957_1565 bad datanode[0] 130.149.21.25:45020
23:35:23,818 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8939771248058631957_1565 in pipeline 130.149.21.25:45020, 130.149.21.33:45020, 130.149.21.60:45020: bad datanode 130.149.21.25:45020
23:35:24,135 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1602036087933829802_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:39396 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:24,136 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1602036087933829802_1565 bad datanode[0] 130.149.21.25:45020
23:35:24,137 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1602036087933829802_1565 in pipeline 130.149.21.25:45020, 130.149.21.33:45020, 130.149.21.28:45020: bad datanode 130.149.21.25:45020
23:35:24,656 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_9009511154512573987_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:39383 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:24,657 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9009511154512573987_1565 bad datanode[0] 130.149.21.25:45020
23:35:24,657 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9009511154512573987_1565 in pipeline 130.149.21.25:45020, 130.149.21.28:45020, 130.149.21.26:45020: bad datanode 130.149.21.25:45020
23:35:25,160 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6022313118885170897_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:39389 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:25,161 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6022313118885170897_1565 bad datanode[0] 130.149.21.25:45020
23:35:25,161 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6022313118885170897_1565 in pipeline 130.149.21.25:45020, 130.149.21.61:45020, 130.149.21.24:45020: bad datanode 130.149.21.25:45020
23:35:25,188 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4510574404504454989_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:39394 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:25,189 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4510574404504454989_1565 bad datanode[0] 130.149.21.25:45020
23:35:25,189 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4510574404504454989_1565 in pipeline 130.149.21.25:45020, 130.149.21.60:45020, 130.149.21.28:45020: bad datanode 130.149.21.25:45020
23:35:26,208 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3705329438426945594_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:39392 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:26,209 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3705329438426945594_1565 bad datanode[0] 130.149.21.25:45020
23:35:26,209 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3705329438426945594_1565 in pipeline 130.149.21.25:45020, 130.149.21.61:45020, 130.149.21.22:45020: bad datanode 130.149.21.25:45020
23:36:29,915 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8939771248058631957_1675java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:49340 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:29,916 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8939771248058631957_1675 bad datanode[0] 130.149.21.33:45020
23:36:29,917 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8939771248058631957_1675 in pipeline 130.149.21.33:45020, 130.149.21.60:45020: bad datanode 130.149.21.33:45020
23:36:30,237 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1602036087933829802_1676java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:49342 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:30,238 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1602036087933829802_1676 bad datanode[0] 130.149.21.33:45020
23:36:30,239 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1602036087933829802_1676 in pipeline 130.149.21.33:45020, 130.149.21.28:45020: bad datanode 130.149.21.33:45020
23:36:30,760 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_9009511154512573987_1677java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:56481 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:30,761 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9009511154512573987_1677 bad datanode[0] 130.149.21.28:45020
23:36:30,762 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9009511154512573987_1677 in pipeline 130.149.21.28:45020, 130.149.21.26:45020: bad datanode 130.149.21.28:45020
23:36:31,265 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6022313118885170897_1678java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:49883 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:31,265 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4510574404504454989_1679java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:45056 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:31,267 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6022313118885170897_1678 bad datanode[0] 130.149.21.61:45020
23:36:31,267 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4510574404504454989_1679 bad datanode[0] 130.149.21.60:45020
23:36:31,268 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6022313118885170897_1678 in pipeline 130.149.21.61:45020, 130.149.21.24:45020: bad datanode 130.149.21.61:45020
23:36:31,268 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4510574404504454989_1679 in pipeline 130.149.21.60:45020, 130.149.21.28:45020: bad datanode 130.149.21.60:45020
23:36:32,309 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3705329438426945594_1680java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:49886 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:32,310 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3705329438426945594_1680 bad datanode[0] 130.149.21.61:45020
23:36:32,311 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3705329438426945594_1680 in pipeline 130.149.21.61:45020, 130.149.21.22:45020: bad datanode 130.149.21.61:45020
23:36:44,983 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3607627421694573503_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:39403 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:44,984 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3607627421694573503_1565 bad datanode[0] 130.149.21.25:45020
23:36:44,985 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3607627421694573503_1565 in pipeline 130.149.21.25:45020, 130.149.21.33:45020, 130.149.21.23:45020: bad datanode 130.149.21.25:45020
23:36:45,903 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5863880717779162677_1674java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:51300 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:45,904 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5863880717779162677_1674 bad datanode[0] 130.149.21.27:45020
23:36:45,904 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5863880717779162677_1674 in pipeline 130.149.21.27:45020, 130.149.21.23:45020: bad datanode 130.149.21.27:45020
