23:29:45,492 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:45,528 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:45,538 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:45,545 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-30 to job manager
23:29:45,610 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:45,610 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:45,611 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:46,722 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:46,741 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:46,751 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:46,751 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,893 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (20/20)
23:30:18,896 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (20/20)
23:30:20,397 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (159/160)
23:30:20,397 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (159/160)
23:30:20,399 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (159/160)
23:30:20,400 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (159/160)
23:30:21,005 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (158/160)
23:30:21,005 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (158/160)
23:30:21,008 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (158/160)
23:30:21,009 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (158/160)
23:30:21,076 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (160/160)
23:30:21,076 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (160/160)
23:30:21,078 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (160/160)
23:30:21,080 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (160/160)
23:30:22,979 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (154/160)
23:30:22,979 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (154/160)
23:30:22,981 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (154/160)
23:30:22,982 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (154/160)
23:30:23,034 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (157/160)
23:30:23,035 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (157/160)
23:30:23,279 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (157/160)
23:30:23,280 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (157/160)
23:30:23,697 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (155/160)
23:30:23,697 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (155/160)
23:30:23,699 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (155/160)
23:30:23,700 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (155/160)
23:30:24,243 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (156/160)
23:30:24,243 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (156/160)
23:30:24,245 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (156/160)
23:30:24,246 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (156/160)
23:30:24,550 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (153/160)
23:30:24,551 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (153/160)
23:30:24,553 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (153/160)
23:30:24,554 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (153/160)
23:31:00,093 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (20/20)
23:31:00,093 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (20/20)
23:34:44,324 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-928671945842756820_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38989 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:44,324 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-928671945842756820_1565 bad datanode[0] 130.149.21.2:45020
23:34:44,325 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-928671945842756820_1565 in pipeline 130.149.21.2:45020, 130.149.21.30:45020, 130.149.21.25:45020: bad datanode 130.149.21.2:45020
23:34:44,973 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6768725067066698326_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38985 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:44,974 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6768725067066698326_1565 bad datanode[0] 130.149.21.2:45020
23:34:44,975 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6768725067066698326_1565 in pipeline 130.149.21.2:45020, 130.149.21.26:45020, 130.149.21.60:45020: bad datanode 130.149.21.2:45020
23:34:47,906 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5078432609798645134_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38992 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:47,907 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5078432609798645134_1565 bad datanode[0] 130.149.21.2:45020
23:34:47,908 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5078432609798645134_1565 in pipeline 130.149.21.2:45020, 130.149.21.21:45020, 130.149.21.30:45020: bad datanode 130.149.21.2:45020
23:34:51,596 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5760440556379415398_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38997 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:51,597 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5760440556379415398_1565 bad datanode[0] 130.149.21.2:45020
23:34:51,598 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5760440556379415398_1565 in pipeline 130.149.21.2:45020, 130.149.21.27:45020, 130.149.21.60:45020: bad datanode 130.149.21.2:45020
23:34:52,150 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-312497490297650058_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:39002 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:52,151 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-312497490297650058_1565 bad datanode[0] 130.149.21.2:45020
23:34:52,152 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-312497490297650058_1565 in pipeline 130.149.21.2:45020, 130.149.21.19:45020, 130.149.21.23:45020: bad datanode 130.149.21.2:45020
23:35:07,829 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4368887046926395558_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:39004 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:07,830 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4368887046926395558_1565 bad datanode[0] 130.149.21.2:45020
23:35:07,831 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4368887046926395558_1565 in pipeline 130.149.21.2:45020, 130.149.21.60:45020, 130.149.21.20:45020: bad datanode 130.149.21.2:45020
23:35:07,834 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2584229350879707636_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38999 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:07,835 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2584229350879707636_1565 bad datanode[0] 130.149.21.2:45020
23:35:07,835 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2584229350879707636_1565 in pipeline 130.149.21.2:45020, 130.149.21.29:45020, 130.149.21.26:45020: bad datanode 130.149.21.2:45020
23:35:28,946 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2505923678580873518_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38994 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:28,947 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2505923678580873518_1565 bad datanode[0] 130.149.21.2:45020
23:35:28,948 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2505923678580873518_1565 in pipeline 130.149.21.2:45020, 130.149.21.3:45020, 130.149.21.60:45020: bad datanode 130.149.21.2:45020
23:35:54,006 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5078432609798645134_1586java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:32897 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:54,007 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5078432609798645134_1586 bad datanode[0] 130.149.21.21:45020
23:35:54,008 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5078432609798645134_1586 in pipeline 130.149.21.21:45020, 130.149.21.30:45020: bad datanode 130.149.21.21:45020
23:35:57,696 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5760440556379415398_1596java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:50056 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:57,697 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5760440556379415398_1596 bad datanode[0] 130.149.21.27:45020
23:35:57,697 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5760440556379415398_1596 in pipeline 130.149.21.27:45020, 130.149.21.60:45020: bad datanode 130.149.21.27:45020
23:35:58,248 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-312497490297650058_1597java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:59139 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:58,249 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-312497490297650058_1597 bad datanode[0] 130.149.21.19:45020
23:35:58,250 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-312497490297650058_1597 in pipeline 130.149.21.19:45020, 130.149.21.23:45020: bad datanode 130.149.21.19:45020
23:36:13,934 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2584229350879707636_1659java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:48087 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:13,935 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4368887046926395558_1658java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:37089 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:13,935 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2584229350879707636_1659 bad datanode[0] 130.149.21.29:45020
23:36:13,936 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4368887046926395558_1658 bad datanode[0] 130.149.21.60:45020
23:36:13,937 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2584229350879707636_1659 in pipeline 130.149.21.29:45020, 130.149.21.26:45020: bad datanode 130.149.21.29:45020
23:36:13,937 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4368887046926395558_1658 in pipeline 130.149.21.60:45020, 130.149.21.20:45020: bad datanode 130.149.21.60:45020
23:36:35,045 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2505923678580873518_1681java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:47804 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:35,045 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2505923678580873518_1681 bad datanode[0] 130.149.21.3:45020
23:36:35,046 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2505923678580873518_1681 in pipeline 130.149.21.3:45020, 130.149.21.60:45020: bad datanode 130.149.21.3:45020
23:36:42,199 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-928671945842756820_1573java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:34520 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:42,200 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-928671945842756820_1573 bad datanode[0] 130.149.21.30:45020
23:36:42,201 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-928671945842756820_1573 in pipeline 130.149.21.30:45020, 130.149.21.25:45020: bad datanode 130.149.21.30:45020
23:36:42,913 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6768725067066698326_1576java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:47183 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:42,914 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6768725067066698326_1576 bad datanode[0] 130.149.21.26:45020
23:36:42,914 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6768725067066698326_1576 in pipeline 130.149.21.26:45020, 130.149.21.60:45020: bad datanode 130.149.21.26:45020
