23:29:43,777 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:43,815 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:43,825 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:43,834 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-22 to job manager
23:29:43,910 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:43,910 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:43,911 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:45,027 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:45,046 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:45,056 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:45,056 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,644 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (14/20)
23:30:18,647 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (14/20)
23:30:20,156 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (111/160)
23:30:20,156 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (111/160)
23:30:20,158 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (111/160)
23:30:20,160 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (111/160)
23:30:21,503 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (112/160)
23:30:21,504 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (112/160)
23:30:21,506 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (112/160)
23:30:21,507 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (112/160)
23:30:21,558 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (108/160)
23:30:21,558 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (108/160)
23:30:21,559 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (108/160)
23:30:21,561 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (108/160)
23:30:22,663 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (105/160)
23:30:22,663 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (105/160)
23:30:22,665 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (105/160)
23:30:22,666 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (105/160)
23:30:23,728 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (110/160)
23:30:23,728 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (110/160)
23:30:23,730 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (110/160)
23:30:23,731 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (110/160)
23:30:23,776 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (106/160)
23:30:23,776 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (106/160)
23:30:23,778 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (106/160)
23:30:23,779 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (106/160)
23:30:24,736 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (109/160)
23:30:24,736 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (109/160)
23:30:24,739 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (109/160)
23:30:24,740 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (109/160)
23:30:24,775 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (107/160)
23:30:24,775 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (107/160)
23:30:24,777 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (107/160)
23:30:24,778 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (107/160)
23:34:45,088 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7714414755259414879_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43679 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:45,089 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7714414755259414879_1565 bad datanode[0] 130.149.21.26:45020
23:34:45,090 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7714414755259414879_1565 in pipeline 130.149.21.26:45020, 130.149.21.18:45020, 130.149.21.61:45020: bad datanode 130.149.21.26:45020
23:34:49,358 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-651660952971067660_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43685 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:49,360 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-651660952971067660_1565 bad datanode[0] 130.149.21.26:45020
23:34:49,361 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-651660952971067660_1565 in pipeline 130.149.21.26:45020, 130.149.21.23:45020, 130.149.21.19:45020: bad datanode 130.149.21.26:45020
23:34:52,748 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_424524987213831730_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43672 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:52,749 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_424524987213831730_1565 bad datanode[0] 130.149.21.26:45020
23:34:52,749 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_424524987213831730_1565 in pipeline 130.149.21.26:45020, 130.149.21.30:45020, 130.149.21.17:45020: bad datanode 130.149.21.26:45020
23:35:00,067 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8407021461316460624_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43677 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:00,068 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8407021461316460624_1565 bad datanode[0] 130.149.21.26:45020
23:35:00,069 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8407021461316460624_1565 in pipeline 130.149.21.26:45020, 130.149.21.28:45020, 130.149.21.22:45020: bad datanode 130.149.21.26:45020
23:35:04,028 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3069378324926818040_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43675 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:04,029 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3069378324926818040_1565 bad datanode[0] 130.149.21.26:45020
23:35:04,030 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3069378324926818040_1565 in pipeline 130.149.21.26:45020, 130.149.21.33:45020, 130.149.21.21:45020: bad datanode 130.149.21.26:45020
23:35:05,647 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_361118591438778928_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43681 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:05,648 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_361118591438778928_1565 bad datanode[0] 130.149.21.26:45020
23:35:05,649 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_361118591438778928_1565 in pipeline 130.149.21.26:45020, 130.149.21.20:45020, 130.149.21.29:45020: bad datanode 130.149.21.26:45020
23:35:07,321 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4583943039922808762_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43688 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:07,323 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4583943039922808762_1565 bad datanode[0] 130.149.21.26:45020
23:35:07,323 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4583943039922808762_1565 in pipeline 130.149.21.26:45020, 130.149.21.18:45020, 130.149.21.25:45020: bad datanode 130.149.21.26:45020
23:35:07,370 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8927021717525274322_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43665 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:07,371 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8927021717525274322_1565 bad datanode[0] 130.149.21.26:45020
23:35:07,371 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8927021717525274322_1565 in pipeline 130.149.21.26:45020, 130.149.21.19:45020, 130.149.21.21:45020: bad datanode 130.149.21.26:45020
23:35:58,843 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_424524987213831730_1598java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:44445 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:58,844 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_424524987213831730_1598 bad datanode[0] 130.149.21.30:45020
23:35:58,845 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_424524987213831730_1598 in pipeline 130.149.21.30:45020, 130.149.21.17:45020: bad datanode 130.149.21.30:45020
23:36:06,170 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8407021461316460624_1616java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:58997 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:06,171 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8407021461316460624_1616 bad datanode[0] 130.149.21.28:45020
23:36:06,171 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8407021461316460624_1616 in pipeline 130.149.21.28:45020, 130.149.21.22:45020: bad datanode 130.149.21.28:45020
23:36:10,133 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3069378324926818040_1636java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:46317 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:10,134 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3069378324926818040_1636 bad datanode[0] 130.149.21.33:45020
23:36:10,135 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3069378324926818040_1636 in pipeline 130.149.21.33:45020, 130.149.21.21:45020: bad datanode 130.149.21.33:45020
23:36:11,749 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_361118591438778928_1649java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:46570 remote=/130.149.21.20:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:11,750 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_361118591438778928_1649 bad datanode[0] 130.149.21.20:45020
23:36:11,750 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_361118591438778928_1649 in pipeline 130.149.21.20:45020, 130.149.21.29:45020: bad datanode 130.149.21.20:45020
23:36:13,423 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4583943039922808762_1656java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:39933 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:13,424 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4583943039922808762_1656 bad datanode[0] 130.149.21.18:45020
23:36:13,425 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4583943039922808762_1656 in pipeline 130.149.21.18:45020, 130.149.21.25:45020: bad datanode 130.149.21.18:45020
23:36:13,467 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8927021717525274322_1657java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:33343 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:13,468 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8927021717525274322_1657 bad datanode[0] 130.149.21.19:45020
23:36:13,469 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8927021717525274322_1657 in pipeline 130.149.21.19:45020, 130.149.21.21:45020: bad datanode 130.149.21.19:45020
23:36:37,331 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7714414755259414879_1577java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:39910 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:37,332 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7714414755259414879_1577 bad datanode[0] 130.149.21.18:45020
23:36:37,332 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7714414755259414879_1577 in pipeline 130.149.21.18:45020, 130.149.21.61:45020: bad datanode 130.149.21.18:45020
23:36:47,446 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-651660952971067660_1594java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:60195 remote=/130.149.21.23:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:47,447 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-651660952971067660_1594 bad datanode[0] 130.149.21.23:45020
23:36:47,447 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-651660952971067660_1594 in pipeline 130.149.21.23:45020, 130.149.21.19:45020: bad datanode 130.149.21.23:45020
