23:29:43,323 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:43,360 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:43,370 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:43,378 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-20 to job manager
23:29:43,442 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:43,443 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:43,444 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:44,564 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:44,584 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:44,594 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:44,594 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,647 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (16/20)
23:30:18,651 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (16/20)
23:30:20,611 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (121/160)
23:30:20,611 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (121/160)
23:30:20,613 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (121/160)
23:30:20,615 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (121/160)
23:30:21,201 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (126/160)
23:30:21,201 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (126/160)
23:30:21,203 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (126/160)
23:30:21,204 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (126/160)
23:30:21,909 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (122/160)
23:30:21,909 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (122/160)
23:30:21,910 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (122/160)
23:30:21,911 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (122/160)
23:30:22,661 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (128/160)
23:30:22,662 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (128/160)
23:30:22,664 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (128/160)
23:30:22,665 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (128/160)
23:30:22,999 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (124/160)
23:30:22,999 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (124/160)
23:30:23,001 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (124/160)
23:30:23,002 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (124/160)
23:30:24,209 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (127/160)
23:30:24,209 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (127/160)
23:30:24,212 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (127/160)
23:30:24,213 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (127/160)
23:30:24,752 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (123/160)
23:30:24,753 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (123/160)
23:30:24,754 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (123/160)
23:30:24,755 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (123/160)
23:30:24,787 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (125/160)
23:30:24,787 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (125/160)
23:30:24,789 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (125/160)
23:30:24,790 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (125/160)
23:31:00,209 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (16/20)
23:31:00,209 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (16/20)
23:34:45,537 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4281282526642754275_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52144 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:45,538 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4281282526642754275_1565 bad datanode[0] 130.149.21.24:45020
23:34:45,539 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4281282526642754275_1565 in pipeline 130.149.21.24:45020, 130.149.21.21:45020, 130.149.21.2:45020: bad datanode 130.149.21.24:45020
23:34:48,009 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4369477025741305356_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52123 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:48,010 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4369477025741305356_1565 bad datanode[0] 130.149.21.24:45020
23:34:48,011 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4369477025741305356_1565 in pipeline 130.149.21.24:45020, 130.149.21.25:45020, 130.149.21.61:45020: bad datanode 130.149.21.24:45020
23:34:51,488 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8578760287070699687_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52138 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:51,489 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8578760287070699687_1565 bad datanode[0] 130.149.21.24:45020
23:34:51,490 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8578760287070699687_1565 in pipeline 130.149.21.24:45020, 130.149.21.19:45020, 130.149.21.18:45020: bad datanode 130.149.21.24:45020
23:34:52,987 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3114313409502530369_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52133 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:52,988 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3114313409502530369_1565 bad datanode[0] 130.149.21.24:45020
23:34:52,989 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3114313409502530369_1565 in pipeline 130.149.21.24:45020, 130.149.21.61:45020, 130.149.21.26:45020: bad datanode 130.149.21.24:45020
23:35:01,124 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2711308972267255219_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52141 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:01,125 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2711308972267255219_1565 bad datanode[0] 130.149.21.24:45020
23:35:01,126 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2711308972267255219_1565 in pipeline 130.149.21.24:45020, 130.149.21.61:45020, 130.149.21.19:45020: bad datanode 130.149.21.24:45020
23:35:01,358 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7397776456528158836_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52129 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:01,358 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7397776456528158836_1565 bad datanode[0] 130.149.21.24:45020
23:35:01,359 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7397776456528158836_1565 in pipeline 130.149.21.24:45020, 130.149.21.19:45020, 130.149.21.30:45020: bad datanode 130.149.21.24:45020
23:35:03,516 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5465855771662270533_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52124 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:03,516 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5465855771662270533_1565 bad datanode[0] 130.149.21.24:45020
23:35:03,517 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5465855771662270533_1565 in pipeline 130.149.21.24:45020, 130.149.21.18:45020, 130.149.21.2:45020: bad datanode 130.149.21.24:45020
23:35:05,359 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5091584683381167259_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52135 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:05,360 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5091584683381167259_1565 bad datanode[0] 130.149.21.24:45020
23:35:05,361 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5091584683381167259_1565 in pipeline 130.149.21.24:45020, 130.149.21.27:45020, 130.149.21.23:45020: bad datanode 130.149.21.24:45020
23:35:54,111 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4369477025741305356_1587java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:55950 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:54,113 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4369477025741305356_1587 bad datanode[0] 130.149.21.25:45020
23:35:54,114 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4369477025741305356_1587 in pipeline 130.149.21.25:45020, 130.149.21.61:45020: bad datanode 130.149.21.25:45020
23:35:57,589 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8578760287070699687_1595java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:51859 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:57,590 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8578760287070699687_1595 bad datanode[0] 130.149.21.19:45020
23:35:57,591 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8578760287070699687_1595 in pipeline 130.149.21.19:45020, 130.149.21.18:45020: bad datanode 130.149.21.19:45020
23:35:59,091 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3114313409502530369_1599java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:59686 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:59,092 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3114313409502530369_1599 bad datanode[0] 130.149.21.61:45020
23:35:59,093 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3114313409502530369_1599 in pipeline 130.149.21.61:45020, 130.149.21.26:45020: bad datanode 130.149.21.61:45020
23:36:07,188 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2711308972267255219_1624java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:59688 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:07,189 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2711308972267255219_1624 bad datanode[0] 130.149.21.61:45020
23:36:07,190 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2711308972267255219_1624 in pipeline 130.149.21.61:45020, 130.149.21.19:45020: bad datanode 130.149.21.61:45020
23:36:07,458 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7397776456528158836_1627java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:51865 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:07,459 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7397776456528158836_1627 bad datanode[0] 130.149.21.19:45020
23:36:07,460 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7397776456528158836_1627 in pipeline 130.149.21.19:45020, 130.149.21.30:45020: bad datanode 130.149.21.19:45020
23:36:09,691 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5465855771662270533_1634java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:33755 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:09,693 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5465855771662270533_1634 bad datanode[0] 130.149.21.18:45020
23:36:09,693 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5465855771662270533_1634 in pipeline 130.149.21.18:45020, 130.149.21.2:45020: bad datanode 130.149.21.18:45020
23:36:11,459 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5091584683381167259_1647java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:40599 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:11,460 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5091584683381167259_1647 bad datanode[0] 130.149.21.27:45020
23:36:11,461 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5091584683381167259_1647 in pipeline 130.149.21.27:45020, 130.149.21.23:45020: bad datanode 130.149.21.27:45020
23:36:28,540 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4281282526642754275_1579java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:56722 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:28,541 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4281282526642754275_1579 bad datanode[0] 130.149.21.21:45020
23:36:28,541 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4281282526642754275_1579 in pipeline 130.149.21.21:45020, 130.149.21.2:45020: bad datanode 130.149.21.21:45020
