23:29:44,182 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:44,219 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:44,228 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:44,236 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-24 to job manager
23:29:44,301 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:44,301 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:44,302 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:45,424 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:45,444 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:45,453 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:45,454 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,775 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (12/20)
23:30:18,778 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (12/20)
23:30:20,948 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (91/160)
23:30:20,948 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (91/160)
23:30:20,951 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (91/160)
23:30:20,953 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (91/160)
23:30:21,538 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (95/160)
23:30:21,538 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (95/160)
23:30:21,540 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (95/160)
23:30:21,541 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (95/160)
23:30:21,646 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (90/160)
23:30:21,646 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (90/160)
23:30:21,648 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (90/160)
23:30:21,649 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (90/160)
23:30:22,645 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (93/160)
23:30:22,645 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (93/160)
23:30:22,647 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (93/160)
23:30:22,648 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (93/160)
23:30:23,033 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (89/160)
23:30:23,033 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (89/160)
23:30:23,035 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (89/160)
23:30:23,037 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (89/160)
23:30:23,057 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (92/160)
23:30:23,057 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (92/160)
23:30:23,059 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (92/160)
23:30:23,060 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (92/160)
23:30:25,041 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (94/160)
23:30:25,042 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (94/160)
23:30:25,044 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (94/160)
23:30:25,045 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (94/160)
23:30:25,354 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (96/160)
23:30:25,354 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (96/160)
23:30:25,357 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (96/160)
23:30:25,358 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (96/160)
23:31:09,835 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (12/20)
23:31:09,836 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (12/20)
23:34:44,159 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_275732685440929618_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46995 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:44,159 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_275732685440929618_1565 bad datanode[0] 130.149.21.28:45020
23:34:44,160 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_275732685440929618_1565 in pipeline 130.149.21.28:45020, 130.149.21.16:45020, 130.149.21.19:45020: bad datanode 130.149.21.28:45020
23:34:48,029 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-518711056372007536_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:47002 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:48,031 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-518711056372007536_1565 bad datanode[0] 130.149.21.28:45020
23:34:48,031 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-518711056372007536_1565 in pipeline 130.149.21.28:45020, 130.149.21.2:45020, 130.149.21.21:45020: bad datanode 130.149.21.28:45020
23:34:56,344 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_207521109137902305_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:47013 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:56,345 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_207521109137902305_1565 bad datanode[0] 130.149.21.28:45020
23:34:56,346 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_207521109137902305_1565 in pipeline 130.149.21.28:45020, 130.149.21.60:45020, 130.149.21.27:45020: bad datanode 130.149.21.28:45020
23:34:57,075 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4975257663127591596_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:47015 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:57,077 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4975257663127591596_1565 bad datanode[0] 130.149.21.28:45020
23:34:57,078 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4975257663127591596_1565 in pipeline 130.149.21.28:45020, 130.149.21.33:45020, 130.149.21.16:45020: bad datanode 130.149.21.28:45020
23:34:59,400 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1686641235584605798_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46997 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:59,401 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1686641235584605798_1565 bad datanode[0] 130.149.21.28:45020
23:34:59,401 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1686641235584605798_1565 in pipeline 130.149.21.28:45020, 130.149.21.61:45020, 130.149.21.60:45020: bad datanode 130.149.21.28:45020
23:35:00,899 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8574910407654487106_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:47004 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:00,900 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8574910407654487106_1565 bad datanode[0] 130.149.21.28:45020
23:35:00,901 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8574910407654487106_1565 in pipeline 130.149.21.28:45020, 130.149.21.2:45020, 130.149.21.29:45020: bad datanode 130.149.21.28:45020
23:35:02,776 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7305913208472542494_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:47008 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:02,776 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7305913208472542494_1565 bad datanode[0] 130.149.21.28:45020
23:35:02,777 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7305913208472542494_1565 in pipeline 130.149.21.28:45020, 130.149.21.30:45020, 130.149.21.22:45020: bad datanode 130.149.21.28:45020
23:35:06,944 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2552119137139546335_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:47010 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:06,945 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2552119137139546335_1565 bad datanode[0] 130.149.21.28:45020
23:35:06,946 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2552119137139546335_1565 in pipeline 130.149.21.28:45020, 130.149.21.61:45020, 130.149.21.22:45020: bad datanode 130.149.21.28:45020
23:36:02,447 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_207521109137902305_1604java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:44724 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:02,449 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_207521109137902305_1604 bad datanode[0] 130.149.21.60:45020
23:36:02,449 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_207521109137902305_1604 in pipeline 130.149.21.60:45020, 130.149.21.27:45020: bad datanode 130.149.21.60:45020
23:36:03,178 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4975257663127591596_1607java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:44710 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:03,179 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4975257663127591596_1607 bad datanode[0] 130.149.21.33:45020
23:36:03,179 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4975257663127591596_1607 in pipeline 130.149.21.33:45020, 130.149.21.16:45020: bad datanode 130.149.21.33:45020
23:36:05,501 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1686641235584605798_1613java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:43868 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:05,502 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1686641235584605798_1613 bad datanode[0] 130.149.21.61:45020
23:36:05,503 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1686641235584605798_1613 in pipeline 130.149.21.61:45020, 130.149.21.60:45020: bad datanode 130.149.21.61:45020
23:36:06,947 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8574910407654487106_1622java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:38611 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:06,949 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8574910407654487106_1622 bad datanode[0] 130.149.21.2:45020
23:36:06,949 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8574910407654487106_1622 in pipeline 130.149.21.2:45020, 130.149.21.29:45020: bad datanode 130.149.21.2:45020
23:36:08,875 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7305913208472542494_1633java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:60904 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:08,876 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7305913208472542494_1633 bad datanode[0] 130.149.21.30:45020
23:36:08,876 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7305913208472542494_1633 in pipeline 130.149.21.30:45020, 130.149.21.22:45020: bad datanode 130.149.21.30:45020
23:36:13,045 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2552119137139546335_1654java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:43879 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:13,046 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2552119137139546335_1654 bad datanode[0] 130.149.21.61:45020
23:36:13,047 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2552119137139546335_1654 in pipeline 130.149.21.61:45020, 130.149.21.22:45020: bad datanode 130.149.21.61:45020
23:36:38,121 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_275732685440929618_1572java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:37088 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:38,122 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_275732685440929618_1572 bad datanode[0] 130.149.21.16:45020
23:36:38,123 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_275732685440929618_1572 in pipeline 130.149.21.16:45020, 130.149.21.19:45020: bad datanode 130.149.21.16:45020
