23:29:42,674 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:42,711 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:42,722 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:42,732 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-17 to job manager
23:29:42,799 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:42,799 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:42,800 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:43,899 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:43,918 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:43,927 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:43,927 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,613 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (4/20)
23:30:18,617 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (4/20)
23:30:21,453 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (30/160)
23:30:21,453 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (30/160)
23:30:21,455 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (30/160)
23:30:21,456 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (30/160)
23:30:22,089 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (32/160)
23:30:22,089 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (32/160)
23:30:22,092 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (32/160)
23:30:22,092 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (32/160)
23:30:22,136 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (27/160)
23:30:22,136 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (27/160)
23:30:22,138 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (27/160)
23:30:22,140 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (27/160)
23:30:22,475 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (26/160)
23:30:22,475 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (26/160)
23:30:22,477 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (26/160)
23:30:22,478 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (26/160)
23:30:22,508 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (29/160)
23:30:22,508 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (29/160)
23:30:22,510 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (29/160)
23:30:22,511 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (29/160)
23:30:23,552 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (28/160)
23:30:23,552 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (28/160)
23:30:23,553 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (28/160)
23:30:23,554 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (28/160)
23:30:24,416 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (25/160)
23:30:24,416 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (25/160)
23:30:24,418 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (25/160)
23:30:24,420 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (25/160)
23:30:24,439 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (31/160)
23:30:24,439 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (31/160)
23:30:24,442 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (31/160)
23:30:24,443 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (31/160)
23:31:23,869 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (4/20)
23:31:23,869 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (4/20)
23:34:45,540 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7347014728302711516_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55718 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:45,541 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7347014728302711516_1565 bad datanode[0] 130.149.21.21:45020
23:34:45,542 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7347014728302711516_1565 in pipeline 130.149.21.21:45020, 130.149.21.28:45020, 130.149.21.26:45020: bad datanode 130.149.21.21:45020
23:34:53,439 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3385714071632893021_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55719 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:53,440 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3385714071632893021_1565 bad datanode[0] 130.149.21.21:45020
23:34:53,440 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3385714071632893021_1565 in pipeline 130.149.21.21:45020, 130.149.21.19:45020, 130.149.21.25:45020: bad datanode 130.149.21.21:45020
23:34:55,926 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2792019715854394927_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55733 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:55,927 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2792019715854394927_1565 bad datanode[0] 130.149.21.21:45020
23:34:55,928 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2792019715854394927_1565 in pipeline 130.149.21.21:45020, 130.149.21.22:45020, 130.149.21.26:45020: bad datanode 130.149.21.21:45020
23:35:04,429 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5537322027700312880_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55717 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:04,430 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5537322027700312880_1565 bad datanode[0] 130.149.21.21:45020
23:35:04,430 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5537322027700312880_1565 in pipeline 130.149.21.21:45020, 130.149.21.19:45020, 130.149.21.60:45020: bad datanode 130.149.21.21:45020
23:35:05,062 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1039504632410807941_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55736 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:05,064 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1039504632410807941_1565 bad datanode[0] 130.149.21.21:45020
23:35:05,064 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1039504632410807941_1565 in pipeline 130.149.21.21:45020, 130.149.21.26:45020, 130.149.21.33:45020: bad datanode 130.149.21.21:45020
23:35:06,130 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2492273878545809134_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55741 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:06,131 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2492273878545809134_1565 bad datanode[0] 130.149.21.21:45020
23:35:06,132 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2492273878545809134_1565 in pipeline 130.149.21.21:45020, 130.149.21.60:45020, 130.149.21.3:45020: bad datanode 130.149.21.21:45020
23:35:06,642 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7080320096462726043_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55720 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:06,643 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7080320096462726043_1565 bad datanode[0] 130.149.21.21:45020
23:35:06,644 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7080320096462726043_1565 in pipeline 130.149.21.21:45020, 130.149.21.29:45020, 130.149.21.19:45020: bad datanode 130.149.21.21:45020
23:35:08,563 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4954089363249585079_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55728 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:08,564 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4954089363249585079_1565 bad datanode[0] 130.149.21.21:45020
23:35:08,564 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4954089363249585079_1565 in pipeline 130.149.21.21:45020, 130.149.21.19:45020, 130.149.21.26:45020: bad datanode 130.149.21.21:45020
23:35:59,482 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3385714071632893021_1600java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:35285 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:59,483 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3385714071632893021_1600 bad datanode[0] 130.149.21.19:45020
23:35:59,484 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3385714071632893021_1600 in pipeline 130.149.21.19:45020, 130.149.21.25:45020: bad datanode 130.149.21.19:45020
23:36:02,026 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2792019715854394927_1603java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:32873 remote=/130.149.21.22:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:02,027 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2792019715854394927_1603 bad datanode[0] 130.149.21.22:45020
23:36:02,028 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2792019715854394927_1603 in pipeline 130.149.21.22:45020, 130.149.21.26:45020: bad datanode 130.149.21.22:45020
23:36:10,531 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5537322027700312880_1640java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:35295 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:10,533 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5537322027700312880_1640 bad datanode[0] 130.149.21.19:45020
23:36:10,533 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5537322027700312880_1640 in pipeline 130.149.21.19:45020, 130.149.21.60:45020: bad datanode 130.149.21.19:45020
23:36:11,163 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1039504632410807941_1643java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:38715 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:11,164 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1039504632410807941_1643 bad datanode[0] 130.149.21.26:45020
23:36:11,165 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1039504632410807941_1643 in pipeline 130.149.21.26:45020, 130.149.21.33:45020: bad datanode 130.149.21.26:45020
23:36:12,228 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2492273878545809134_1650java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:42449 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:12,229 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2492273878545809134_1650 bad datanode[0] 130.149.21.60:45020
23:36:12,230 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2492273878545809134_1650 in pipeline 130.149.21.60:45020, 130.149.21.3:45020: bad datanode 130.149.21.60:45020
23:36:12,742 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7080320096462726043_1652java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:45461 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:12,743 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7080320096462726043_1652 bad datanode[0] 130.149.21.29:45020
23:36:12,744 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7080320096462726043_1652 in pipeline 130.149.21.29:45020, 130.149.21.19:45020: bad datanode 130.149.21.29:45020
23:36:14,665 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4954089363249585079_1663java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:35304 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:14,667 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4954089363249585079_1663 bad datanode[0] 130.149.21.19:45020
23:36:14,667 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4954089363249585079_1663 in pipeline 130.149.21.19:45020, 130.149.21.26:45020: bad datanode 130.149.21.19:45020
23:36:44,157 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7347014728302711516_1578java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:44088 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:44,158 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7347014728302711516_1578 bad datanode[0] 130.149.21.28:45020
23:36:44,159 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7347014728302711516_1578 in pipeline 130.149.21.28:45020, 130.149.21.26:45020: bad datanode 130.149.21.28:45020
