23:29:41,799 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:41,836 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:41,846 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:41,854 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-13 to job manager
23:29:41,919 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:41,919 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:41,920 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:43,014 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:43,032 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:43,041 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:43,042 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,732 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (8/20)
23:30:18,735 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (8/20)
23:30:20,115 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (60/160)
23:30:20,115 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (60/160)
23:30:20,117 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (60/160)
23:30:20,119 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (60/160)
23:30:20,706 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (62/160)
23:30:20,706 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (62/160)
23:30:20,709 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (62/160)
23:30:20,710 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (62/160)
23:30:21,121 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (61/160)
23:30:21,122 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (61/160)
23:30:21,123 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (61/160)
23:30:21,125 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (61/160)
23:30:21,650 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (64/160)
23:30:21,650 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (64/160)
23:30:21,653 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (64/160)
23:30:21,654 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (64/160)
23:30:21,673 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (57/160)
23:30:21,673 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (57/160)
23:30:21,676 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (57/160)
23:30:21,677 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (57/160)
23:30:23,196 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (63/160)
23:30:23,196 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (63/160)
23:30:23,198 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (63/160)
23:30:23,199 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (63/160)
23:30:23,445 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (58/160)
23:30:23,445 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (58/160)
23:30:23,447 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (58/160)
23:30:23,448 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (58/160)
23:30:24,071 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (59/160)
23:30:24,071 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (59/160)
23:30:24,074 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (59/160)
23:30:24,075 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (59/160)
23:34:00,278 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (8/20)
23:34:00,278 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (8/20)
23:34:44,066 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8006445652796972645_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58081 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:44,067 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8006445652796972645_1565 bad datanode[0] 130.149.21.17:45020
23:34:44,068 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8006445652796972645_1565 in pipeline 130.149.21.17:45020, 130.149.21.21:45020, 130.149.21.25:45020: bad datanode 130.149.21.17:45020
23:34:48,891 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2589577575617331332_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58093 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:48,893 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2589577575617331332_1565 bad datanode[0] 130.149.21.17:45020
23:34:48,893 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2589577575617331332_1565 in pipeline 130.149.21.17:45020, 130.149.21.21:45020, 130.149.21.19:45020: bad datanode 130.149.21.17:45020
23:35:00,757 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7411002168373522331_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58083 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:00,758 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7411002168373522331_1565 bad datanode[0] 130.149.21.17:45020
23:35:00,758 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7411002168373522331_1565 in pipeline 130.149.21.17:45020, 130.149.21.23:45020, 130.149.21.2:45020: bad datanode 130.149.21.17:45020
23:35:04,242 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2025916293555354212_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58085 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:04,243 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2025916293555354212_1565 bad datanode[0] 130.149.21.17:45020
23:35:04,244 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2025916293555354212_1565 in pipeline 130.149.21.17:45020, 130.149.21.25:45020, 130.149.21.33:45020: bad datanode 130.149.21.17:45020
23:35:04,961 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4010392709957047738_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58091 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:04,962 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4010392709957047738_1565 bad datanode[0] 130.149.21.17:45020
23:35:04,963 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4010392709957047738_1565 in pipeline 130.149.21.17:45020, 130.149.21.24:45020, 130.149.21.28:45020: bad datanode 130.149.21.17:45020
23:35:07,174 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-835479044679631831_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58089 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:07,175 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-835479044679631831_1565 bad datanode[0] 130.149.21.17:45020
23:35:07,175 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-835479044679631831_1565 in pipeline 130.149.21.17:45020, 130.149.21.24:45020, 130.149.21.26:45020: bad datanode 130.149.21.17:45020
23:35:08,374 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8310834576822236681_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58079 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:08,375 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8310834576822236681_1565 bad datanode[0] 130.149.21.17:45020
23:35:08,376 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8310834576822236681_1565 in pipeline 130.149.21.17:45020, 130.149.21.22:45020, 130.149.21.3:45020: bad datanode 130.149.21.17:45020
23:35:41,169 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-42554086367344601_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58076 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:41,170 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-42554086367344601_1565 bad datanode[0] 130.149.21.17:45020
23:35:41,171 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-42554086367344601_1565 in pipeline 130.149.21.17:45020, 130.149.21.24:45020, 130.149.21.29:45020: bad datanode 130.149.21.17:45020
23:36:06,855 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7411002168373522331_1621java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:38324 remote=/130.149.21.23:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:06,856 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7411002168373522331_1621 bad datanode[0] 130.149.21.23:45020
23:36:06,857 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7411002168373522331_1621 in pipeline 130.149.21.23:45020, 130.149.21.2:45020: bad datanode 130.149.21.23:45020
23:36:10,343 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2025916293555354212_1639java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:36338 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:10,345 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2025916293555354212_1639 bad datanode[0] 130.149.21.25:45020
23:36:10,345 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2025916293555354212_1639 in pipeline 130.149.21.25:45020, 130.149.21.33:45020: bad datanode 130.149.21.25:45020
23:36:11,065 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4010392709957047738_1642java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:46771 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:11,066 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4010392709957047738_1642 bad datanode[0] 130.149.21.24:45020
23:36:11,067 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4010392709957047738_1642 in pipeline 130.149.21.24:45020, 130.149.21.28:45020: bad datanode 130.149.21.24:45020
23:36:13,216 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-835479044679631831_1655java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:46775 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:13,217 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-835479044679631831_1655 bad datanode[0] 130.149.21.24:45020
23:36:13,218 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-835479044679631831_1655 in pipeline 130.149.21.24:45020, 130.149.21.26:45020: bad datanode 130.149.21.24:45020
23:36:14,474 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8310834576822236681_1660java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:53314 remote=/130.149.21.22:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:14,475 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8310834576822236681_1660 bad datanode[0] 130.149.21.22:45020
23:36:14,476 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8310834576822236681_1660 in pipeline 130.149.21.22:45020, 130.149.21.3:45020: bad datanode 130.149.21.22:45020
23:36:38,046 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8006445652796972645_1571java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:55049 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:38,048 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8006445652796972645_1571 bad datanode[0] 130.149.21.21:45020
23:36:38,048 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8006445652796972645_1571 in pipeline 130.149.21.21:45020, 130.149.21.25:45020: bad datanode 130.149.21.21:45020
23:36:38,146 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2589577575617331332_1591java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:55051 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:38,148 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2589577575617331332_1591 bad datanode[0] 130.149.21.21:45020
23:36:38,148 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2589577575617331332_1591 in pipeline 130.149.21.21:45020, 130.149.21.19:45020: bad datanode 130.149.21.21:45020
23:36:47,268 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-42554086367344601_1683java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:46781 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:47,270 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-42554086367344601_1683 bad datanode[0] 130.149.21.24:45020
23:36:47,270 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-42554086367344601_1683 in pipeline 130.149.21.24:45020, 130.149.21.29:45020: bad datanode 130.149.21.24:45020
