23:29:45,280 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:45,317 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:45,327 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:45,335 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-29 to job manager
23:29:45,400 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:45,400 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:45,401 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:46,515 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:46,533 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:46,543 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:46,543 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,601 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (19/20)
23:30:18,605 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (19/20)
23:30:21,666 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (147/160)
23:30:21,666 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (147/160)
23:30:21,668 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (147/160)
23:30:21,669 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (147/160)
23:30:22,253 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (152/160)
23:30:22,254 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (152/160)
23:30:22,255 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (152/160)
23:30:22,257 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (152/160)
23:30:22,290 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (150/160)
23:30:22,290 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (150/160)
23:30:22,292 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (150/160)
23:30:22,293 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (150/160)
23:30:22,628 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (151/160)
23:30:22,629 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (151/160)
23:30:22,631 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (151/160)
23:30:22,632 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (151/160)
23:30:23,073 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (145/160)
23:30:23,073 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (145/160)
23:30:23,075 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (145/160)
23:30:23,076 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (145/160)
23:30:24,078 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (148/160)
23:30:24,079 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (148/160)
23:30:24,080 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (148/160)
23:30:24,081 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (148/160)
23:30:24,520 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (146/160)
23:30:24,520 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (146/160)
23:30:24,522 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (146/160)
23:30:24,523 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (146/160)
23:30:24,833 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (149/160)
23:30:24,833 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (149/160)
23:30:24,835 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (149/160)
23:30:24,836 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (149/160)
23:30:56,127 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (19/20)
23:30:56,128 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (19/20)
23:34:43,420 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4174313927396924205_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47449 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:43,420 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4174313927396924205_1565 bad datanode[0] 130.149.21.3:45020
23:34:43,421 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4174313927396924205_1565 in pipeline 130.149.21.3:45020, 130.149.21.26:45020, 130.149.21.24:45020: bad datanode 130.149.21.3:45020
23:34:47,879 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5048101969394064557_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47433 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:47,880 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5048101969394064557_1565 bad datanode[0] 130.149.21.3:45020
23:34:47,881 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5048101969394064557_1565 in pipeline 130.149.21.3:45020, 130.149.21.18:45020, 130.149.21.25:45020: bad datanode 130.149.21.3:45020
23:34:59,724 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3235893230513557579_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47447 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:59,725 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3235893230513557579_1565 bad datanode[0] 130.149.21.3:45020
23:34:59,726 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3235893230513557579_1565 in pipeline 130.149.21.3:45020, 130.149.21.27:45020, 130.149.21.25:45020: bad datanode 130.149.21.3:45020
23:35:00,432 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3452888352599008324_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47445 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:00,433 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3452888352599008324_1565 bad datanode[0] 130.149.21.3:45020
23:35:00,433 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3452888352599008324_1565 in pipeline 130.149.21.3:45020, 130.149.21.19:45020, 130.149.21.30:45020: bad datanode 130.149.21.3:45020
23:35:01,227 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4476990327973431310_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47435 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:01,228 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4476990327973431310_1565 bad datanode[0] 130.149.21.3:45020
23:35:01,229 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4476990327973431310_1565 in pipeline 130.149.21.3:45020, 130.149.21.28:45020, 130.149.21.61:45020: bad datanode 130.149.21.3:45020
23:35:05,350 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6269127532021858766_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47442 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:05,350 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6269127532021858766_1565 bad datanode[0] 130.149.21.3:45020
23:35:05,351 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6269127532021858766_1565 in pipeline 130.149.21.3:45020, 130.149.21.23:45020, 130.149.21.17:45020: bad datanode 130.149.21.3:45020
23:35:08,455 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5716903721897393660_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47439 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:08,456 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5716903721897393660_1565 bad datanode[0] 130.149.21.3:45020
23:35:08,457 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5716903721897393660_1565 in pipeline 130.149.21.3:45020, 130.149.21.16:45020, 130.149.21.18:45020: bad datanode 130.149.21.3:45020
23:35:08,931 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7023041139178127514_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47451 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:08,932 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7023041139178127514_1565 bad datanode[0] 130.149.21.3:45020
23:35:08,932 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7023041139178127514_1565 in pipeline 130.149.21.3:45020, 130.149.21.18:45020, 130.149.21.17:45020: bad datanode 130.149.21.3:45020
23:35:53,946 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5048101969394064557_1585java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:42009 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:53,947 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5048101969394064557_1585 bad datanode[0] 130.149.21.18:45020
23:35:53,948 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5048101969394064557_1585 in pipeline 130.149.21.18:45020, 130.149.21.25:45020: bad datanode 130.149.21.18:45020
23:36:05,763 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3235893230513557579_1614java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:50307 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:05,764 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3235893230513557579_1614 bad datanode[0] 130.149.21.27:45020
23:36:05,765 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3235893230513557579_1614 in pipeline 130.149.21.27:45020, 130.149.21.25:45020: bad datanode 130.149.21.27:45020
23:36:06,536 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3452888352599008324_1619java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:34750 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:06,537 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3452888352599008324_1619 bad datanode[0] 130.149.21.19:45020
23:36:06,538 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3452888352599008324_1619 in pipeline 130.149.21.19:45020, 130.149.21.30:45020: bad datanode 130.149.21.19:45020
23:36:07,329 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4476990327973431310_1626java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:43798 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:07,330 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4476990327973431310_1626 bad datanode[0] 130.149.21.28:45020
23:36:07,330 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4476990327973431310_1626 in pipeline 130.149.21.28:45020, 130.149.21.61:45020: bad datanode 130.149.21.28:45020
23:36:11,450 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6269127532021858766_1646java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:49005 remote=/130.149.21.23:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:11,451 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6269127532021858766_1646 bad datanode[0] 130.149.21.23:45020
23:36:11,451 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6269127532021858766_1646 in pipeline 130.149.21.23:45020, 130.149.21.17:45020: bad datanode 130.149.21.23:45020
23:36:14,556 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5716903721897393660_1662java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:43052 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:14,557 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5716903721897393660_1662 bad datanode[0] 130.149.21.16:45020
23:36:14,558 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5716903721897393660_1662 in pipeline 130.149.21.16:45020, 130.149.21.18:45020: bad datanode 130.149.21.16:45020
23:36:15,031 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7023041139178127514_1665java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:42025 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:15,032 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7023041139178127514_1665 bad datanode[0] 130.149.21.18:45020
23:36:15,032 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7023041139178127514_1665 in pipeline 130.149.21.18:45020, 130.149.21.17:45020: bad datanode 130.149.21.18:45020
23:36:30,485 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4174313927396924205_1569java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:36459 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:30,487 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4174313927396924205_1569 bad datanode[0] 130.149.21.26:45020
23:36:30,487 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4174313927396924205_1569 in pipeline 130.149.21.26:45020, 130.149.21.24:45020: bad datanode 130.149.21.26:45020
