23:29:42,250 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:29:42,287 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:29:42,298 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:29:42,307 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-15 to job manager
23:29:42,376 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:29:42,376 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:29:42,377 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:29:43,479 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:29:43,499 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:29:43,510 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:29:43,510 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:30:18,904 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (6/20)
23:30:18,906 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (6/20)
23:30:21,404 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (41/160)
23:30:21,405 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (41/160)
23:30:21,406 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (41/160)
23:30:21,407 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (41/160)
23:30:22,089 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (43/160)
23:30:22,089 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (43/160)
23:30:22,091 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (43/160)
23:30:22,092 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (43/160)
23:30:22,121 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (44/160)
23:30:22,121 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (44/160)
23:30:22,123 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (44/160)
23:30:22,124 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (44/160)
23:30:22,184 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (47/160)
23:30:22,184 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (47/160)
23:30:22,186 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (47/160)
23:30:22,187 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (47/160)
23:30:22,517 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (42/160)
23:30:22,517 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (42/160)
23:30:22,519 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (42/160)
23:30:22,520 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (42/160)
23:30:22,756 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (45/160)
23:30:22,756 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (45/160)
23:30:22,758 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (45/160)
23:30:22,759 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (45/160)
23:30:24,128 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (48/160)
23:30:24,129 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (48/160)
23:30:24,131 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (48/160)
23:30:24,132 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (48/160)
23:30:24,160 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (46/160)
23:30:24,160 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (46/160)
23:30:24,162 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (46/160)
23:30:24,163 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (46/160)
23:32:52,908 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (6/20)
23:32:52,908 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (6/20)
23:34:43,499 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7450265898989061740_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:35477 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:43,500 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7450265898989061740_1565 bad datanode[0] 130.149.21.19:45020
23:34:43,501 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7450265898989061740_1565 in pipeline 130.149.21.19:45020, 130.149.21.27:45020, 130.149.21.17:45020: bad datanode 130.149.21.19:45020
23:34:44,888 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8924124737404705858_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:35485 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:44,889 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8924124737404705858_1565 bad datanode[0] 130.149.21.19:45020
23:34:44,890 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8924124737404705858_1565 in pipeline 130.149.21.19:45020, 130.149.21.27:45020, 130.149.21.26:45020: bad datanode 130.149.21.19:45020
23:34:46,231 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1434598694063830566_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:35500 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:46,232 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1434598694063830566_1565 bad datanode[0] 130.149.21.19:45020
23:34:46,233 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1434598694063830566_1565 in pipeline 130.149.21.19:45020, 130.149.21.30:45020, 130.149.21.28:45020: bad datanode 130.149.21.19:45020
23:34:47,612 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3927478221160166063_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:35487 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:47,613 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3927478221160166063_1565 bad datanode[0] 130.149.21.19:45020
23:34:47,613 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3927478221160166063_1565 in pipeline 130.149.21.19:45020, 130.149.21.30:45020, 130.149.21.28:45020: bad datanode 130.149.21.19:45020
23:34:57,537 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5873704733220945127_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:35489 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:34:57,538 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5873704733220945127_1565 bad datanode[0] 130.149.21.19:45020
23:34:57,539 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5873704733220945127_1565 in pipeline 130.149.21.19:45020, 130.149.21.26:45020, 130.149.21.23:45020: bad datanode 130.149.21.19:45020
23:35:02,399 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-470846889523187789_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:35483 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:02,399 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-470846889523187789_1565 bad datanode[0] 130.149.21.19:45020
23:35:02,400 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-470846889523187789_1565 in pipeline 130.149.21.19:45020, 130.149.21.27:45020, 130.149.21.25:45020: bad datanode 130.149.21.19:45020
23:35:04,075 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-708662497023710451_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:35494 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:04,076 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-708662497023710451_1565 bad datanode[0] 130.149.21.19:45020
23:35:04,077 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-708662497023710451_1565 in pipeline 130.149.21.19:45020, 130.149.21.60:45020, 130.149.21.22:45020: bad datanode 130.149.21.19:45020
23:35:40,068 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-355776223480840539_1565java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:35503 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:40,069 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-355776223480840539_1565 bad datanode[0] 130.149.21.19:45020
23:35:40,070 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-355776223480840539_1565 in pipeline 130.149.21.19:45020, 130.149.21.27:45020, 130.149.21.61:45020: bad datanode 130.149.21.19:45020
23:35:53,712 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3927478221160166063_1584java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:43031 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:35:53,713 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3927478221160166063_1584 bad datanode[0] 130.149.21.30:45020
23:35:53,714 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3927478221160166063_1584 in pipeline 130.149.21.30:45020, 130.149.21.28:45020: bad datanode 130.149.21.30:45020
23:36:03,639 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5873704733220945127_1608java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:46838 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:03,640 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5873704733220945127_1608 bad datanode[0] 130.149.21.26:45020
23:36:03,641 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5873704733220945127_1608 in pipeline 130.149.21.26:45020, 130.149.21.23:45020: bad datanode 130.149.21.26:45020
23:36:08,496 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-470846889523187789_1631java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:41719 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:08,498 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-470846889523187789_1631 bad datanode[0] 130.149.21.27:45020
23:36:08,498 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-470846889523187789_1631 in pipeline 130.149.21.27:45020, 130.149.21.25:45020: bad datanode 130.149.21.27:45020
23:36:10,176 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-708662497023710451_1637java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:55405 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:10,177 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-708662497023710451_1637 bad datanode[0] 130.149.21.60:45020
23:36:10,178 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-708662497023710451_1637 in pipeline 130.149.21.60:45020, 130.149.21.22:45020: bad datanode 130.149.21.60:45020
23:36:36,579 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7450265898989061740_1570java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:41696 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:36,580 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7450265898989061740_1570 bad datanode[0] 130.149.21.27:45020
23:36:36,580 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7450265898989061740_1570 in pipeline 130.149.21.27:45020, 130.149.21.17:45020: bad datanode 130.149.21.27:45020
23:36:43,876 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8924124737404705858_1575java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:41698 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:43,878 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8924124737404705858_1575 bad datanode[0] 130.149.21.27:45020
23:36:43,878 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8924124737404705858_1575 in pipeline 130.149.21.27:45020, 130.149.21.26:45020: bad datanode 130.149.21.27:45020
23:36:44,117 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1434598694063830566_1581java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:43029 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:44,118 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1434598694063830566_1581 bad datanode[0] 130.149.21.30:45020
23:36:44,119 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1434598694063830566_1581 in pipeline 130.149.21.30:45020, 130.149.21.28:45020: bad datanode 130.149.21.30:45020
23:36:46,170 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-355776223480840539_1682java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:41740 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:36:46,171 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-355776223480840539_1682 bad datanode[0] 130.149.21.27:45020
23:36:46,172 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-355776223480840539_1682 in pipeline 130.149.21.27:45020, 130.149.21.61:45020: bad datanode 130.149.21.27:45020
