22:46:10,953 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
22:46:10,991 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
22:46:11,000 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
22:46:11,008 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-25 to job manager
22:46:11,072 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
22:46:11,073 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
22:46:11,074 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
22:46:12,193 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
22:46:12,212 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
22:46:12,221 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
22:46:12,222 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
22:46:46,455 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (14/25)
22:46:46,457 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (14/25)
22:46:48,339 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (107/200)
22:46:48,339 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (107/200)
22:46:48,341 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (107/200)
22:46:48,343 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (107/200)
22:46:49,241 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (111/200)
22:46:49,241 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (111/200)
22:46:49,243 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (111/200)
22:46:49,244 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (111/200)
22:46:50,028 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (110/200)
22:46:50,028 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (110/200)
22:46:50,030 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (110/200)
22:46:50,031 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (110/200)
22:46:51,332 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (108/200)
22:46:51,333 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (108/200)
22:46:51,335 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (108/200)
22:46:51,336 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (108/200)
22:46:51,668 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (112/200)
22:46:51,668 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (112/200)
22:46:51,670 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (112/200)
22:46:51,671 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (112/200)
22:46:52,078 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (106/200)
22:46:52,079 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (106/200)
22:46:52,080 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (106/200)
22:46:52,081 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (106/200)
22:46:52,406 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (105/200)
22:46:52,406 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (105/200)
22:46:52,408 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (105/200)
22:46:52,409 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (105/200)
22:46:52,730 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (109/200)
22:46:52,730 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (109/200)
22:46:52,732 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (109/200)
22:46:52,733 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (109/200)
22:49:24,649 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1740087224761073739_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:56078 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:24,650 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1740087224761073739_1722 bad datanode[0] 130.149.21.29:45020
22:49:24,651 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1740087224761073739_1722 in pipeline 130.149.21.29:45020, 130.149.21.27:45020, 130.149.21.17:45020: bad datanode 130.149.21.29:45020
22:49:31,077 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6626371829359194862_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:56093 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:31,078 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6626371829359194862_1722 bad datanode[0] 130.149.21.29:45020
22:49:31,079 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6626371829359194862_1722 in pipeline 130.149.21.29:45020, 130.149.21.65:45020, 130.149.21.64:45020: bad datanode 130.149.21.29:45020
22:49:31,255 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5596956617759494533_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:56074 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:31,255 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5596956617759494533_1722 bad datanode[0] 130.149.21.29:45020
22:49:31,256 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5596956617759494533_1722 in pipeline 130.149.21.29:45020, 130.149.21.19:45020, 130.149.21.18:45020: bad datanode 130.149.21.29:45020
22:49:31,746 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4603711061336119517_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:56076 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:31,747 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4603711061336119517_1722 bad datanode[0] 130.149.21.29:45020
22:49:31,748 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4603711061336119517_1722 in pipeline 130.149.21.29:45020, 130.149.21.22:45020, 130.149.21.2:45020: bad datanode 130.149.21.29:45020
22:49:51,294 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6182710269492193807_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:56096 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:51,295 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6182710269492193807_1722 bad datanode[0] 130.149.21.29:45020
22:49:51,296 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6182710269492193807_1722 in pipeline 130.149.21.29:45020, 130.149.21.25:45020, 130.149.21.65:45020: bad datanode 130.149.21.29:45020
22:49:59,236 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8768317356310905730_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:56089 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:59,237 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8768317356310905730_1722 bad datanode[0] 130.149.21.29:45020
22:49:59,237 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8768317356310905730_1722 in pipeline 130.149.21.29:45020, 130.149.21.25:45020, 130.149.21.63:45020: bad datanode 130.149.21.29:45020
22:50:11,719 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4660266064311759868_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:56083 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:11,720 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4660266064311759868_1722 bad datanode[0] 130.149.21.29:45020
22:50:11,721 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4660266064311759868_1722 in pipeline 130.149.21.29:45020, 130.149.21.25:45020, 130.149.21.61:45020: bad datanode 130.149.21.29:45020
22:50:12,969 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7606888946241593235_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:56081 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:12,970 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7606888946241593235_1722 bad datanode[0] 130.149.21.29:45020
22:50:12,970 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7606888946241593235_1722 in pipeline 130.149.21.29:45020, 130.149.21.19:45020, 130.149.21.16:45020: bad datanode 130.149.21.29:45020
22:50:30,765 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1740087224761073739_1738java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:47942 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:30,766 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1740087224761073739_1738 bad datanode[0] 130.149.21.27:45020
22:50:30,766 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1740087224761073739_1738 in pipeline 130.149.21.27:45020, 130.149.21.17:45020: bad datanode 130.149.21.27:45020
22:50:37,174 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6626371829359194862_1773java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:37004 remote=/130.149.21.65:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:37,176 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6626371829359194862_1773 bad datanode[0] 130.149.21.65:45020
22:50:37,176 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6626371829359194862_1773 in pipeline 130.149.21.65:45020, 130.149.21.64:45020: bad datanode 130.149.21.65:45020
22:50:37,370 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5596956617759494533_1776java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:51223 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:37,371 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5596956617759494533_1776 bad datanode[0] 130.149.21.19:45020
22:50:37,371 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5596956617759494533_1776 in pipeline 130.149.21.19:45020, 130.149.21.18:45020: bad datanode 130.149.21.19:45020
22:50:37,869 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4603711061336119517_1777java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:34447 remote=/130.149.21.22:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:37,870 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4603711061336119517_1777 bad datanode[0] 130.149.21.22:45020
22:50:37,871 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4603711061336119517_1777 in pipeline 130.149.21.22:45020, 130.149.21.2:45020: bad datanode 130.149.21.22:45020
22:50:57,396 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6182710269492193807_1805java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:40194 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:57,397 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6182710269492193807_1805 bad datanode[0] 130.149.21.25:45020
22:50:57,398 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6182710269492193807_1805 in pipeline 130.149.21.25:45020, 130.149.21.65:45020: bad datanode 130.149.21.25:45020
22:51:05,338 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8768317356310905730_1821java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:40201 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:05,339 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8768317356310905730_1821 bad datanode[0] 130.149.21.25:45020
22:51:05,339 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8768317356310905730_1821 in pipeline 130.149.21.25:45020, 130.149.21.63:45020: bad datanode 130.149.21.25:45020
22:51:17,817 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4660266064311759868_1862java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:40206 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:17,819 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4660266064311759868_1862 bad datanode[0] 130.149.21.25:45020
22:51:17,820 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4660266064311759868_1862 in pipeline 130.149.21.25:45020, 130.149.21.61:45020: bad datanode 130.149.21.25:45020
22:51:19,069 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7606888946241593235_1867java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:51242 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:19,070 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7606888946241593235_1867 bad datanode[0] 130.149.21.19:45020
22:51:19,071 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7606888946241593235_1867 in pipeline 130.149.21.19:45020, 130.149.21.16:45020: bad datanode 130.149.21.19:45020
