22:46:08,569 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
22:46:08,606 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
22:46:08,616 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
22:46:08,624 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-14 to job manager
22:46:08,690 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
22:46:08,690 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
22:46:08,691 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
22:46:09,790 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
22:46:09,809 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
22:46:09,818 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
22:46:09,818 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
22:46:46,208 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (5/25)
22:46:46,212 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (5/25)
22:46:49,044 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (39/200)
22:46:49,044 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (39/200)
22:46:49,046 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (39/200)
22:46:49,047 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (39/200)
22:46:49,703 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (34/200)
22:46:49,703 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (34/200)
22:46:49,704 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (34/200)
22:46:49,706 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (34/200)
22:46:50,566 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (37/200)
22:46:50,566 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (37/200)
22:46:50,568 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (37/200)
22:46:50,569 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (37/200)
22:46:50,629 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (35/200)
22:46:50,630 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (35/200)
22:46:50,868 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (35/200)
22:46:50,869 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (35/200)
22:46:50,894 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (40/200)
22:46:50,894 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (40/200)
22:46:50,896 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (40/200)
22:46:50,898 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (40/200)
22:46:51,284 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (38/200)
22:46:51,285 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (38/200)
22:46:51,286 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (38/200)
22:46:51,287 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (38/200)
22:46:51,646 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (36/200)
22:46:51,646 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (36/200)
22:46:51,648 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (36/200)
22:46:51,649 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (36/200)
22:46:52,310 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (33/200)
22:46:52,311 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (33/200)
22:46:52,312 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (33/200)
22:46:52,313 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (33/200)
22:47:21,772 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (5/25)
22:47:21,772 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (5/25)
22:49:27,316 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3798552804202581741_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:57235 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:27,317 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3798552804202581741_1722 bad datanode[0] 130.149.21.18:45020
22:49:27,318 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3798552804202581741_1722 in pipeline 130.149.21.18:45020, 130.149.21.23:45020, 130.149.21.66:45020: bad datanode 130.149.21.18:45020
22:49:28,527 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-9152499041383506114_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:57239 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:28,528 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-9152499041383506114_1722 bad datanode[0] 130.149.21.18:45020
22:49:28,529 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-9152499041383506114_1722 in pipeline 130.149.21.18:45020, 130.149.21.28:45020, 130.149.21.21:45020: bad datanode 130.149.21.18:45020
22:49:28,800 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6813522676660371934_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:57233 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:28,801 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6813522676660371934_1722 bad datanode[0] 130.149.21.18:45020
22:49:28,801 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6813522676660371934_1722 in pipeline 130.149.21.18:45020, 130.149.21.27:45020, 130.149.21.64:45020: bad datanode 130.149.21.18:45020
22:49:40,715 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1928003265057139357_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:57228 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:40,716 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1928003265057139357_1722 bad datanode[0] 130.149.21.18:45020
22:49:40,716 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1928003265057139357_1722 in pipeline 130.149.21.18:45020, 130.149.21.33:45020, 130.149.21.24:45020: bad datanode 130.149.21.18:45020
22:49:51,031 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2614656001781868735_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:57237 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:51,032 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2614656001781868735_1722 bad datanode[0] 130.149.21.18:45020
22:49:51,033 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2614656001781868735_1722 in pipeline 130.149.21.18:45020, 130.149.21.60:45020, 130.149.21.3:45020: bad datanode 130.149.21.18:45020
22:50:05,035 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4518547685315110590_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:57245 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:05,036 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4518547685315110590_1722 bad datanode[0] 130.149.21.18:45020
22:50:05,036 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4518547685315110590_1722 in pipeline 130.149.21.18:45020, 130.149.21.29:45020, 130.149.21.34:45020: bad datanode 130.149.21.18:45020
22:50:07,437 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1219039308787944523_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:57231 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:07,438 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1219039308787944523_1722 bad datanode[0] 130.149.21.18:45020
22:50:07,438 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1219039308787944523_1722 in pipeline 130.149.21.18:45020, 130.149.21.23:45020, 130.149.21.29:45020: bad datanode 130.149.21.18:45020
22:50:10,906 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8848070585291592045_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:57243 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:10,907 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8848070585291592045_1722 bad datanode[0] 130.149.21.18:45020
22:50:10,908 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8848070585291592045_1722 in pipeline 130.149.21.18:45020, 130.149.21.27:45020, 130.149.21.61:45020: bad datanode 130.149.21.18:45020
22:50:33,388 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3798552804202581741_1750java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:58115 remote=/130.149.21.23:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:33,389 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3798552804202581741_1750 bad datanode[0] 130.149.21.23:45020
22:50:33,389 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3798552804202581741_1750 in pipeline 130.149.21.23:45020, 130.149.21.66:45020: bad datanode 130.149.21.23:45020
22:50:34,627 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-9152499041383506114_1758java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:46748 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:34,628 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-9152499041383506114_1758 bad datanode[0] 130.149.21.28:45020
22:50:34,629 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-9152499041383506114_1758 in pipeline 130.149.21.28:45020, 130.149.21.21:45020: bad datanode 130.149.21.28:45020
22:50:34,902 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6813522676660371934_1759java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:54720 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:34,903 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6813522676660371934_1759 bad datanode[0] 130.149.21.27:45020
22:50:34,903 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6813522676660371934_1759 in pipeline 130.149.21.27:45020, 130.149.21.64:45020: bad datanode 130.149.21.27:45020
22:50:46,817 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1928003265057139357_1788java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:54635 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:46,817 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1928003265057139357_1788 bad datanode[0] 130.149.21.33:45020
22:50:46,818 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1928003265057139357_1788 in pipeline 130.149.21.33:45020, 130.149.21.24:45020: bad datanode 130.149.21.33:45020
22:50:57,136 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2614656001781868735_1803java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:60258 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:57,137 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2614656001781868735_1803 bad datanode[0] 130.149.21.60:45020
22:50:57,137 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2614656001781868735_1803 in pipeline 130.149.21.60:45020, 130.149.21.3:45020: bad datanode 130.149.21.60:45020
22:51:11,134 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4518547685315110590_1833java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:56313 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:11,136 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4518547685315110590_1833 bad datanode[0] 130.149.21.29:45020
22:51:11,136 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4518547685315110590_1833 in pipeline 130.149.21.29:45020, 130.149.21.34:45020: bad datanode 130.149.21.29:45020
22:51:13,535 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1219039308787944523_1843java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:58135 remote=/130.149.21.23:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:13,536 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1219039308787944523_1843 bad datanode[0] 130.149.21.23:45020
22:51:13,537 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1219039308787944523_1843 in pipeline 130.149.21.23:45020, 130.149.21.29:45020: bad datanode 130.149.21.23:45020
22:51:17,005 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8848070585291592045_1858java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.18:54740 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:17,007 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8848070585291592045_1858 bad datanode[0] 130.149.21.27:45020
22:51:17,007 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8848070585291592045_1858 in pipeline 130.149.21.27:45020, 130.149.21.61:45020: bad datanode 130.149.21.27:45020
