22:46:12,942 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
22:46:12,979 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
22:46:12,988 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
22:46:12,997 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-34 to job manager
22:46:13,062 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
22:46:13,062 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
22:46:13,063 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
22:46:14,174 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
22:46:14,192 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
22:46:14,202 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
22:46:14,202 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
22:46:46,193 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (21/25)
22:46:46,195 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (21/25)
22:46:48,742 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (164/200)
22:46:48,743 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (164/200)
22:46:48,744 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (164/200)
22:46:48,746 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (164/200)
22:46:49,415 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (163/200)
22:46:49,416 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (163/200)
22:46:49,417 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (163/200)
22:46:49,418 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (163/200)
22:46:49,437 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (162/200)
22:46:49,437 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (162/200)
22:46:49,439 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (162/200)
22:46:49,440 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (162/200)
22:46:51,393 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (168/200)
22:46:51,394 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (168/200)
22:46:51,395 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (168/200)
22:46:51,397 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (168/200)
22:46:51,701 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (161/200)
22:46:51,702 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (161/200)
22:46:51,703 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (161/200)
22:46:51,704 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (161/200)
22:46:52,029 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (165/200)
22:46:52,029 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (165/200)
22:46:52,031 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (165/200)
22:46:52,032 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (165/200)
22:46:52,051 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (167/200)
22:46:52,051 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (167/200)
22:46:52,053 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (167/200)
22:46:52,054 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (167/200)
22:46:52,075 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (166/200)
22:46:52,075 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (166/200)
22:46:52,077 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (166/200)
22:46:52,078 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (166/200)
22:47:20,839 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (21/25)
22:47:20,839 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (21/25)
22:49:24,590 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3476244284940774260_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:53336 remote=/130.149.21.64:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:24,591 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3476244284940774260_1722 bad datanode[0] 130.149.21.64:45020
22:49:24,592 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3476244284940774260_1722 in pipeline 130.149.21.64:45020, 130.149.21.21:45020, 130.149.21.28:45020: bad datanode 130.149.21.64:45020
22:50:04,261 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7408347995193767656_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:53339 remote=/130.149.21.64:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:04,263 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7408347995193767656_1722 bad datanode[0] 130.149.21.64:45020
22:50:04,263 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7408347995193767656_1722 in pipeline 130.149.21.64:45020, 130.149.21.33:45020, 130.149.21.3:45020: bad datanode 130.149.21.64:45020
22:50:04,897 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-267437728670973603_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:53330 remote=/130.149.21.64:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:04,898 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-267437728670973603_1722 bad datanode[0] 130.149.21.64:45020
22:50:04,899 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-267437728670973603_1722 in pipeline 130.149.21.64:45020, 130.149.21.28:45020, 130.149.21.20:45020: bad datanode 130.149.21.64:45020
22:50:06,258 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3364778782827856729_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:53351 remote=/130.149.21.64:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:06,259 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3364778782827856729_1722 bad datanode[0] 130.149.21.64:45020
22:50:06,260 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3364778782827856729_1722 in pipeline 130.149.21.64:45020, 130.149.21.23:45020, 130.149.21.29:45020: bad datanode 130.149.21.64:45020
22:50:10,245 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8645621730102514047_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:53355 remote=/130.149.21.64:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:10,247 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8645621730102514047_1722 bad datanode[0] 130.149.21.64:45020
22:50:10,247 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8645621730102514047_1722 in pipeline 130.149.21.64:45020, 130.149.21.23:45020, 130.149.21.17:45020: bad datanode 130.149.21.64:45020
22:50:11,771 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8629334258096726290_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:53341 remote=/130.149.21.64:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:11,772 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8629334258096726290_1722 bad datanode[0] 130.149.21.64:45020
22:50:11,773 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8629334258096726290_1722 in pipeline 130.149.21.64:45020, 130.149.21.19:45020, 130.149.21.3:45020: bad datanode 130.149.21.64:45020
22:50:13,859 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3902416366199092217_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:53334 remote=/130.149.21.64:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:13,860 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3902416366199092217_1722 bad datanode[0] 130.149.21.64:45020
22:50:13,860 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3902416366199092217_1722 in pipeline 130.149.21.64:45020, 130.149.21.3:45020, 130.149.21.21:45020: bad datanode 130.149.21.64:45020
22:50:17,729 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1331885896381181650_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:53343 remote=/130.149.21.64:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:17,730 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1331885896381181650_1722 bad datanode[0] 130.149.21.64:45020
22:50:17,731 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1331885896381181650_1722 in pipeline 130.149.21.64:45020, 130.149.21.61:45020, 130.149.21.60:45020: bad datanode 130.149.21.64:45020
22:50:30,709 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3476244284940774260_1737java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:60781 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:30,711 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3476244284940774260_1737 bad datanode[0] 130.149.21.21:45020
22:50:30,711 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3476244284940774260_1737 in pipeline 130.149.21.21:45020, 130.149.21.28:45020: bad datanode 130.149.21.21:45020
22:51:10,365 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7408347995193767656_1826java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:55673 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:10,366 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7408347995193767656_1826 bad datanode[0] 130.149.21.33:45020
22:51:10,367 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7408347995193767656_1826 in pipeline 130.149.21.33:45020, 130.149.21.3:45020: bad datanode 130.149.21.33:45020
22:51:10,997 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-267437728670973603_1832java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:45851 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:10,999 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-267437728670973603_1832 bad datanode[0] 130.149.21.28:45020
22:51:10,999 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-267437728670973603_1832 in pipeline 130.149.21.28:45020, 130.149.21.20:45020: bad datanode 130.149.21.28:45020
22:51:12,357 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3364778782827856729_1837java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:48882 remote=/130.149.21.23:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:12,358 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3364778782827856729_1837 bad datanode[0] 130.149.21.23:45020
22:51:12,359 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3364778782827856729_1837 in pipeline 130.149.21.23:45020, 130.149.21.29:45020: bad datanode 130.149.21.23:45020
22:51:16,345 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8645621730102514047_1853java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:48886 remote=/130.149.21.23:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:16,346 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8645621730102514047_1853 bad datanode[0] 130.149.21.23:45020
22:51:16,347 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8645621730102514047_1853 in pipeline 130.149.21.23:45020, 130.149.21.17:45020: bad datanode 130.149.21.23:45020
22:51:17,872 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8629334258096726290_1864java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:57570 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:17,873 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8629334258096726290_1864 bad datanode[0] 130.149.21.19:45020
22:51:17,874 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8629334258096726290_1864 in pipeline 130.149.21.19:45020, 130.149.21.3:45020: bad datanode 130.149.21.19:45020
22:51:19,958 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3902416366199092217_1869java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:41261 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:19,959 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3902416366199092217_1869 bad datanode[0] 130.149.21.3:45020
22:51:19,960 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3902416366199092217_1869 in pipeline 130.149.21.3:45020, 130.149.21.21:45020: bad datanode 130.149.21.3:45020
22:51:23,826 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1331885896381181650_1878java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.64:60160 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:23,828 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1331885896381181650_1878 bad datanode[0] 130.149.21.61:45020
22:51:23,828 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1331885896381181650_1878 in pipeline 130.149.21.61:45020, 130.149.21.60:45020: bad datanode 130.149.21.61:45020
