22:46:08,794 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
22:46:08,830 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
22:46:08,841 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
22:46:08,850 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-15 to job manager
22:46:08,919 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
22:46:08,920 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
22:46:08,921 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
22:46:10,019 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
22:46:10,040 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
22:46:10,050 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
22:46:10,051 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
22:46:46,828 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (6/25)
22:46:46,832 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (6/25)
22:46:47,623 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (43/200)
22:46:47,623 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (43/200)
22:46:47,625 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (43/200)
22:46:47,627 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (43/200)
22:46:48,214 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (44/200)
22:46:48,216 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (44/200)
22:46:48,217 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (44/200)
22:46:48,220 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (44/200)
22:46:49,299 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (42/200)
22:46:49,299 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (42/200)
22:46:49,300 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (42/200)
22:46:49,301 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (42/200)
22:46:49,878 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (41/200)
22:46:49,878 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (41/200)
22:46:49,880 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (41/200)
22:46:49,881 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (41/200)
22:46:50,294 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (47/200)
22:46:50,295 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (47/200)
22:46:50,297 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (47/200)
22:46:50,298 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (47/200)
22:46:50,837 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (46/200)
22:46:50,837 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (46/200)
22:46:50,839 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (46/200)
22:46:50,840 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (46/200)
22:46:51,653 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (48/200)
22:46:51,653 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (48/200)
22:46:51,655 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (48/200)
22:46:51,656 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (48/200)
22:46:51,956 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (45/200)
22:46:51,956 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (45/200)
22:46:51,957 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (45/200)
22:46:51,959 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (45/200)
22:47:53,714 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (6/25)
22:47:53,715 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (6/25)
22:49:27,639 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_920303488876528141_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:60009 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:27,639 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_920303488876528141_1722 bad datanode[0] 130.149.21.19:45020
22:49:27,641 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_920303488876528141_1722 in pipeline 130.149.21.19:45020, 130.149.21.26:45020, 130.149.21.30:45020: bad datanode 130.149.21.19:45020
22:49:29,580 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1028479087686989934_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:59999 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:29,581 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1028479087686989934_1722 bad datanode[0] 130.149.21.19:45020
22:49:29,581 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1028479087686989934_1722 in pipeline 130.149.21.19:45020, 130.149.21.28:45020, 130.149.21.34:45020: bad datanode 130.149.21.19:45020
22:49:30,079 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3391702893922120515_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:60015 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:30,080 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3391702893922120515_1722 bad datanode[0] 130.149.21.19:45020
22:49:30,081 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3391702893922120515_1722 in pipeline 130.149.21.19:45020, 130.149.21.3:45020, 130.149.21.20:45020: bad datanode 130.149.21.19:45020
22:49:34,140 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4528645763303814547_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:60011 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:34,141 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4528645763303814547_1722 bad datanode[0] 130.149.21.19:45020
22:49:34,142 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4528645763303814547_1722 in pipeline 130.149.21.19:45020, 130.149.21.24:45020, 130.149.21.61:45020: bad datanode 130.149.21.19:45020
22:49:52,959 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1862959176558284161_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:60013 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:52,960 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1862959176558284161_1722 bad datanode[0] 130.149.21.19:45020
22:49:52,960 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1862959176558284161_1722 in pipeline 130.149.21.19:45020, 130.149.21.64:45020, 130.149.21.27:45020: bad datanode 130.149.21.19:45020
22:49:55,613 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3376522238473698559_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:60003 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:49:55,614 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3376522238473698559_1722 bad datanode[0] 130.149.21.19:45020
22:49:55,615 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3376522238473698559_1722 in pipeline 130.149.21.19:45020, 130.149.21.22:45020, 130.149.21.23:45020: bad datanode 130.149.21.19:45020
22:50:10,811 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3487677096700302534_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:60006 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:10,812 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3487677096700302534_1722 bad datanode[0] 130.149.21.19:45020
22:50:10,812 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3487677096700302534_1722 in pipeline 130.149.21.19:45020, 130.149.21.66:45020, 130.149.21.22:45020: bad datanode 130.149.21.19:45020
22:50:16,677 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4300424136070268362_1722java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:59994 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:16,678 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4300424136070268362_1722 bad datanode[0] 130.149.21.19:45020
22:50:16,679 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4300424136070268362_1722 in pipeline 130.149.21.19:45020, 130.149.21.23:45020, 130.149.21.26:45020: bad datanode 130.149.21.19:45020
22:50:33,762 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_920303488876528141_1754java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:43098 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:33,763 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_920303488876528141_1754 bad datanode[0] 130.149.21.26:45020
22:50:33,764 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_920303488876528141_1754 in pipeline 130.149.21.26:45020, 130.149.21.30:45020: bad datanode 130.149.21.26:45020
22:50:35,680 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1028479087686989934_1765java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:41046 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:35,682 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1028479087686989934_1765 bad datanode[0] 130.149.21.28:45020
22:50:35,682 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1028479087686989934_1765 in pipeline 130.149.21.28:45020, 130.149.21.34:45020: bad datanode 130.149.21.28:45020
22:50:36,210 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3391702893922120515_1770java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:44860 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:36,212 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3391702893922120515_1770 bad datanode[0] 130.149.21.3:45020
22:50:36,212 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3391702893922120515_1770 in pipeline 130.149.21.3:45020, 130.149.21.20:45020: bad datanode 130.149.21.3:45020
22:50:40,253 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4528645763303814547_1781java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:55043 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:40,254 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4528645763303814547_1781 bad datanode[0] 130.149.21.24:45020
22:50:40,255 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4528645763303814547_1781 in pipeline 130.149.21.24:45020, 130.149.21.61:45020: bad datanode 130.149.21.24:45020
22:50:59,058 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1862959176558284161_1812java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:36052 remote=/130.149.21.64:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:50:59,059 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1862959176558284161_1812 bad datanode[0] 130.149.21.64:45020
22:50:59,059 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1862959176558284161_1812 in pipeline 130.149.21.64:45020, 130.149.21.27:45020: bad datanode 130.149.21.64:45020
22:51:01,712 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3376522238473698559_1815java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:39182 remote=/130.149.21.22:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:01,713 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3376522238473698559_1815 bad datanode[0] 130.149.21.22:45020
22:51:01,714 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3376522238473698559_1815 in pipeline 130.149.21.22:45020, 130.149.21.23:45020: bad datanode 130.149.21.22:45020
22:51:16,907 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3487677096700302534_1857java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:45012 remote=/130.149.21.66:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:16,909 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3487677096700302534_1857 bad datanode[0] 130.149.21.66:45020
22:51:16,909 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3487677096700302534_1857 in pipeline 130.149.21.66:45020, 130.149.21.22:45020: bad datanode 130.149.21.66:45020
22:51:22,778 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4300424136070268362_1876java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.19:42371 remote=/130.149.21.23:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

22:51:22,779 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4300424136070268362_1876 bad datanode[0] 130.149.21.23:45020
22:51:22,779 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4300424136070268362_1876 in pipeline 130.149.21.23:45020, 130.149.21.26:45020: bad datanode 130.149.21.23:45020
