23:21:11,893 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:11,930 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:11,940 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:11,948 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-17 to job manager
23:21:12,013 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:12,014 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:12,015 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:13,120 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:13,139 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:13,149 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:13,149 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:47,622 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (4/20)
23:21:47,624 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (4/20)
23:21:49,757 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (30/160)
23:21:49,757 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (30/160)
23:21:49,759 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (30/160)
23:21:49,760 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (30/160)
23:21:50,336 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (27/160)
23:21:50,336 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (27/160)
23:21:50,339 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (27/160)
23:21:50,340 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (27/160)
23:21:50,377 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (32/160)
23:21:50,377 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (32/160)
23:21:50,379 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (32/160)
23:21:50,380 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (32/160)
23:21:50,778 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (26/160)
23:21:50,778 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (26/160)
23:21:50,779 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (26/160)
23:21:50,780 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (26/160)
23:21:50,798 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (25/160)
23:21:50,799 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (25/160)
23:21:50,800 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (25/160)
23:21:50,801 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (25/160)
23:21:50,817 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (28/160)
23:21:50,817 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (28/160)
23:21:50,818 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (28/160)
23:21:50,819 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (28/160)
23:21:51,221 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (29/160)
23:21:51,221 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (29/160)
23:21:51,223 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (29/160)
23:21:51,224 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (29/160)
23:21:53,728 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (31/160)
23:21:53,728 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (31/160)
23:21:53,730 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (31/160)
23:21:53,731 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (31/160)
23:23:00,836 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (4/20)
23:23:00,836 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (4/20)
23:25:55,821 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1184964542761313247_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55606 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:55,822 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1184964542761313247_1161 bad datanode[0] 130.149.21.21:45020
23:25:55,823 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1184964542761313247_1161 in pipeline 130.149.21.21:45020, 130.149.21.26:45020, 130.149.21.19:45020: bad datanode 130.149.21.21:45020
23:25:57,176 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2952290953826913042_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55615 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:57,177 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2952290953826913042_1161 bad datanode[0] 130.149.21.21:45020
23:25:57,177 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2952290953826913042_1161 in pipeline 130.149.21.21:45020, 130.149.21.61:45020, 130.149.21.28:45020: bad datanode 130.149.21.21:45020
23:26:01,939 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5562906212147364763_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55608 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:01,940 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5562906212147364763_1161 bad datanode[0] 130.149.21.21:45020
23:26:01,941 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5562906212147364763_1161 in pipeline 130.149.21.21:45020, 130.149.21.16:45020, 130.149.21.19:45020: bad datanode 130.149.21.21:45020
23:26:03,692 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5526087856108221862_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55617 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:03,693 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5526087856108221862_1161 bad datanode[0] 130.149.21.21:45020
23:26:03,693 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5526087856108221862_1161 in pipeline 130.149.21.21:45020, 130.149.21.61:45020, 130.149.21.25:45020: bad datanode 130.149.21.21:45020
23:26:05,310 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6215520399621469772_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55621 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:05,311 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6215520399621469772_1161 bad datanode[0] 130.149.21.21:45020
23:26:05,312 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6215520399621469772_1161 in pipeline 130.149.21.21:45020, 130.149.21.28:45020, 130.149.21.26:45020: bad datanode 130.149.21.21:45020
23:26:06,333 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-474280232311943475_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55600 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:06,333 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-474280232311943475_1161 bad datanode[0] 130.149.21.21:45020
23:26:06,334 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-474280232311943475_1161 in pipeline 130.149.21.21:45020, 130.149.21.60:45020, 130.149.21.2:45020: bad datanode 130.149.21.21:45020
23:26:08,406 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3795646977381264884_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55610 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:08,407 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3795646977381264884_1161 bad datanode[0] 130.149.21.21:45020
23:26:08,408 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3795646977381264884_1161 in pipeline 130.149.21.21:45020, 130.149.21.24:45020, 130.149.21.27:45020: bad datanode 130.149.21.21:45020
23:26:11,889 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5774842247564895821_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:55604 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:11,890 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5774842247564895821_1161 bad datanode[0] 130.149.21.21:45020
23:26:11,891 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5774842247564895821_1161 in pipeline 130.149.21.21:45020, 130.149.21.22:45020, 130.149.21.3:45020: bad datanode 130.149.21.21:45020
23:27:02,020 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1184964542761313247_1172java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:38572 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:02,021 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1184964542761313247_1172 bad datanode[0] 130.149.21.26:45020
23:27:02,022 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1184964542761313247_1172 in pipeline 130.149.21.26:45020, 130.149.21.19:45020: bad datanode 130.149.21.26:45020
23:27:03,321 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2952290953826913042_1181java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:54258 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:03,323 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2952290953826913042_1181 bad datanode[0] 130.149.21.61:45020
23:27:03,323 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2952290953826913042_1181 in pipeline 130.149.21.61:45020, 130.149.21.28:45020: bad datanode 130.149.21.61:45020
23:27:08,043 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5562906212147364763_1212java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:50535 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:08,044 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5562906212147364763_1212 bad datanode[0] 130.149.21.16:45020
23:27:08,045 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5562906212147364763_1212 in pipeline 130.149.21.16:45020, 130.149.21.19:45020: bad datanode 130.149.21.16:45020
23:27:09,792 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5526087856108221862_1219java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:54267 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:09,793 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5526087856108221862_1219 bad datanode[0] 130.149.21.61:45020
23:27:09,793 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5526087856108221862_1219 in pipeline 130.149.21.61:45020, 130.149.21.25:45020: bad datanode 130.149.21.61:45020
23:27:11,412 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6215520399621469772_1226java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:43976 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:11,414 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6215520399621469772_1226 bad datanode[0] 130.149.21.28:45020
23:27:11,414 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6215520399621469772_1226 in pipeline 130.149.21.28:45020, 130.149.21.26:45020: bad datanode 130.149.21.28:45020
23:27:12,430 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-474280232311943475_1231java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:42318 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:12,431 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-474280232311943475_1231 bad datanode[0] 130.149.21.60:45020
23:27:12,432 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-474280232311943475_1231 in pipeline 130.149.21.60:45020, 130.149.21.2:45020: bad datanode 130.149.21.60:45020
23:27:14,511 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3795646977381264884_1242java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:36521 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:14,512 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3795646977381264884_1242 bad datanode[0] 130.149.21.24:45020
23:27:14,513 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3795646977381264884_1242 in pipeline 130.149.21.24:45020, 130.149.21.27:45020: bad datanode 130.149.21.24:45020
23:27:17,990 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5774842247564895821_1262java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.21:60994 remote=/130.149.21.22:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:17,991 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5774842247564895821_1262 bad datanode[0] 130.149.21.22:45020
23:27:17,992 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5774842247564895821_1262 in pipeline 130.149.21.22:45020, 130.149.21.3:45020: bad datanode 130.149.21.22:45020
