23:21:14,533 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:14,570 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:14,580 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:14,587 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-29 to job manager
23:21:14,652 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:14,652 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:14,653 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:15,778 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:15,797 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:15,806 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:15,807 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:47,061 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (19/20)
23:21:47,064 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (19/20)
23:21:49,610 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (151/160)
23:21:49,611 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (151/160)
23:21:49,613 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (151/160)
23:21:49,614 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (151/160)
23:21:50,211 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (150/160)
23:21:50,212 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (150/160)
23:21:50,213 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (150/160)
23:21:50,214 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (150/160)
23:21:50,588 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (147/160)
23:21:50,588 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (147/160)
23:21:50,590 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (147/160)
23:21:50,591 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (147/160)
23:21:52,243 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (152/160)
23:21:52,244 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (152/160)
23:21:52,244 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (152/160)
23:21:52,246 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (152/160)
23:21:52,290 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (145/160)
23:21:52,290 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (145/160)
23:21:52,488 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (145/160)
23:21:52,490 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (145/160)
23:21:52,804 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (146/160)
23:21:52,804 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (146/160)
23:21:52,806 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (146/160)
23:21:52,807 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (146/160)
23:21:53,275 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (148/160)
23:21:53,275 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (148/160)
23:21:53,277 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (148/160)
23:21:53,278 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (148/160)
23:21:53,574 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (149/160)
23:21:53,574 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (149/160)
23:21:53,576 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (149/160)
23:21:53,577 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (149/160)
23:22:28,259 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (19/20)
23:22:28,259 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (19/20)
23:25:53,984 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2745186078635470579_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47207 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:53,985 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2745186078635470579_1161 bad datanode[0] 130.149.21.3:45020
23:25:53,985 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2745186078635470579_1161 in pipeline 130.149.21.3:45020, 130.149.21.17:45020, 130.149.21.24:45020: bad datanode 130.149.21.3:45020
23:25:57,828 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_9217198775522917700_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47218 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:57,829 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9217198775522917700_1161 bad datanode[0] 130.149.21.3:45020
23:25:57,829 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9217198775522917700_1161 in pipeline 130.149.21.3:45020, 130.149.21.18:45020, 130.149.21.17:45020: bad datanode 130.149.21.3:45020
23:25:58,183 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8600896740816386512_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47221 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:58,184 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8600896740816386512_1161 bad datanode[0] 130.149.21.3:45020
23:25:58,184 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8600896740816386512_1161 in pipeline 130.149.21.3:45020, 130.149.21.21:45020, 130.149.21.33:45020: bad datanode 130.149.21.3:45020
23:25:58,851 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_457555246412069178_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47209 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:58,852 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_457555246412069178_1161 bad datanode[0] 130.149.21.3:45020
23:25:58,853 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_457555246412069178_1161 in pipeline 130.149.21.3:45020, 130.149.21.17:45020, 130.149.21.27:45020: bad datanode 130.149.21.3:45020
23:26:04,446 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3599530057936331976_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47216 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:04,447 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3599530057936331976_1161 bad datanode[0] 130.149.21.3:45020
23:26:04,448 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3599530057936331976_1161 in pipeline 130.149.21.3:45020, 130.149.21.19:45020, 130.149.21.60:45020: bad datanode 130.149.21.3:45020
23:26:07,301 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1158717458974862992_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47211 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:07,302 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1158717458974862992_1161 bad datanode[0] 130.149.21.3:45020
23:26:07,302 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1158717458974862992_1161 in pipeline 130.149.21.3:45020, 130.149.21.26:45020, 130.149.21.60:45020: bad datanode 130.149.21.3:45020
23:26:07,368 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5212550668582469975_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47228 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:07,369 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5212550668582469975_1161 bad datanode[0] 130.149.21.3:45020
23:26:07,370 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5212550668582469975_1161 in pipeline 130.149.21.3:45020, 130.149.21.33:45020, 130.149.21.23:45020: bad datanode 130.149.21.3:45020
23:26:09,018 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4138579081592607859_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:47226 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:09,019 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4138579081592607859_1161 bad datanode[0] 130.149.21.3:45020
23:26:09,019 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4138579081592607859_1161 in pipeline 130.149.21.3:45020, 130.149.21.30:45020, 130.149.21.29:45020: bad datanode 130.149.21.3:45020
23:27:00,188 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2745186078635470579_1163java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:33679 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:00,189 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2745186078635470579_1163 bad datanode[0] 130.149.21.17:45020
23:27:00,189 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2745186078635470579_1163 in pipeline 130.149.21.17:45020, 130.149.21.24:45020: bad datanode 130.149.21.17:45020
23:27:03,934 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_9217198775522917700_1188java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:41789 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:03,935 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9217198775522917700_1188 bad datanode[0] 130.149.21.18:45020
23:27:03,935 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9217198775522917700_1188 in pipeline 130.149.21.18:45020, 130.149.21.17:45020: bad datanode 130.149.21.18:45020
23:27:04,283 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8600896740816386512_1194java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:41127 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:04,284 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8600896740816386512_1194 bad datanode[0] 130.149.21.21:45020
23:27:04,284 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8600896740816386512_1194 in pipeline 130.149.21.21:45020, 130.149.21.33:45020: bad datanode 130.149.21.21:45020
23:27:04,958 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_457555246412069178_1200java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:33688 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:04,959 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_457555246412069178_1200 bad datanode[0] 130.149.21.17:45020
23:27:04,960 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_457555246412069178_1200 in pipeline 130.149.21.17:45020, 130.149.21.27:45020: bad datanode 130.149.21.17:45020
23:27:10,550 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3599530057936331976_1224java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:34532 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:10,551 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3599530057936331976_1224 bad datanode[0] 130.149.21.19:45020
23:27:10,551 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3599530057936331976_1224 in pipeline 130.149.21.19:45020, 130.149.21.60:45020: bad datanode 130.149.21.19:45020
23:27:13,406 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1158717458974862992_1238java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:36250 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:13,406 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5212550668582469975_1239java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:60510 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:13,407 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1158717458974862992_1238 bad datanode[0] 130.149.21.26:45020
23:27:13,408 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5212550668582469975_1239 bad datanode[0] 130.149.21.33:45020
23:27:13,409 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1158717458974862992_1238 in pipeline 130.149.21.26:45020, 130.149.21.60:45020: bad datanode 130.149.21.26:45020
23:27:13,409 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5212550668582469975_1239 in pipeline 130.149.21.33:45020, 130.149.21.23:45020: bad datanode 130.149.21.33:45020
23:27:15,125 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4138579081592607859_1245java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.3:36658 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:15,125 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4138579081592607859_1245 bad datanode[0] 130.149.21.30:45020
23:27:15,126 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4138579081592607859_1245 in pipeline 130.149.21.30:45020, 130.149.21.29:45020: bad datanode 130.149.21.30:45020
