23:21:13,645 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:13,682 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:13,692 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:13,699 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-25 to job manager
23:21:13,764 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:13,764 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:13,765 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:14,881 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:14,901 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:14,918 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:14,918 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:47,789 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (13/20)
23:21:47,791 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (13/20)
23:21:50,247 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (99/160)
23:21:50,248 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (99/160)
23:21:50,250 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (99/160)
23:21:50,251 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (99/160)
23:21:50,832 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (97/160)
23:21:50,832 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (97/160)
23:21:50,834 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (97/160)
23:21:50,835 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (97/160)
23:21:51,268 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (103/160)
23:21:51,268 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (103/160)
23:21:51,270 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (103/160)
23:21:51,271 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (103/160)
23:21:51,795 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (104/160)
23:21:51,795 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (104/160)
23:21:51,796 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (104/160)
23:21:51,797 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (104/160)
23:21:52,124 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (102/160)
23:21:52,125 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (102/160)
23:21:52,126 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (102/160)
23:21:52,127 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (102/160)
23:21:52,825 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (100/160)
23:21:52,825 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (100/160)
23:21:52,827 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (100/160)
23:21:52,828 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (100/160)
23:21:53,138 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (101/160)
23:21:53,138 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (101/160)
23:21:53,140 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (101/160)
23:21:53,141 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (101/160)
23:21:53,189 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (98/160)
23:21:53,189 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (98/160)
23:21:53,438 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (98/160)
23:21:53,439 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (98/160)
23:22:28,763 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (13/20)
23:22:28,763 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (13/20)
23:25:54,409 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2131758028850097019_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60536 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:54,409 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2131758028850097019_1161 bad datanode[0] 130.149.21.29:45020
23:25:54,410 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2131758028850097019_1161 in pipeline 130.149.21.29:45020, 130.149.21.23:45020, 130.149.21.2:45020: bad datanode 130.149.21.29:45020
23:25:57,222 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-501133499023382088_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60542 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:57,223 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-501133499023382088_1161 bad datanode[0] 130.149.21.29:45020
23:25:57,224 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-501133499023382088_1161 in pipeline 130.149.21.29:45020, 130.149.21.60:45020, 130.149.21.23:45020: bad datanode 130.149.21.29:45020
23:25:58,601 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7637743788496593220_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60546 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:58,602 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7637743788496593220_1161 bad datanode[0] 130.149.21.29:45020
23:25:58,603 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7637743788496593220_1161 in pipeline 130.149.21.29:45020, 130.149.21.60:45020, 130.149.21.33:45020: bad datanode 130.149.21.29:45020
23:25:59,190 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1137466152275748739_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60544 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:59,191 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1137466152275748739_1161 bad datanode[0] 130.149.21.29:45020
23:25:59,192 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1137466152275748739_1161 in pipeline 130.149.21.29:45020, 130.149.21.17:45020, 130.149.21.3:45020: bad datanode 130.149.21.29:45020
23:26:05,255 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2289969600566882656_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60540 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:05,256 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2289969600566882656_1161 bad datanode[0] 130.149.21.29:45020
23:26:05,257 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2289969600566882656_1161 in pipeline 130.149.21.29:45020, 130.149.21.17:45020, 130.149.21.60:45020: bad datanode 130.149.21.29:45020
23:26:07,243 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8294391577281870958_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60530 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:07,243 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8294391577281870958_1161 bad datanode[0] 130.149.21.29:45020
23:26:07,244 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8294391577281870958_1161 in pipeline 130.149.21.29:45020, 130.149.21.61:45020, 130.149.21.17:45020: bad datanode 130.149.21.29:45020
23:26:09,915 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_585828411013470731_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60529 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:09,916 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_585828411013470731_1161 bad datanode[0] 130.149.21.29:45020
23:26:09,916 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_585828411013470731_1161 in pipeline 130.149.21.29:45020, 130.149.21.19:45020, 130.149.21.30:45020: bad datanode 130.149.21.29:45020
23:26:36,515 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2738560298258090871_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:60538 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:36,516 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2738560298258090871_1161 bad datanode[0] 130.149.21.29:45020
23:26:36,517 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2738560298258090871_1161 in pipeline 130.149.21.29:45020, 130.149.21.3:45020, 130.149.21.27:45020: bad datanode 130.149.21.29:45020
23:27:00,591 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2131758028850097019_1167java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:49806 remote=/130.149.21.23:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:00,593 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2131758028850097019_1167 bad datanode[0] 130.149.21.23:45020
23:27:00,593 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2131758028850097019_1167 in pipeline 130.149.21.23:45020, 130.149.21.2:45020: bad datanode 130.149.21.23:45020
23:27:03,328 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-501133499023382088_1182java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:50580 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:03,330 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-501133499023382088_1182 bad datanode[0] 130.149.21.60:45020
23:27:03,330 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-501133499023382088_1182 in pipeline 130.149.21.60:45020, 130.149.21.23:45020: bad datanode 130.149.21.60:45020
23:27:04,706 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7637743788496593220_1198java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:50582 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:04,707 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7637743788496593220_1198 bad datanode[0] 130.149.21.60:45020
23:27:04,708 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7637743788496593220_1198 in pipeline 130.149.21.60:45020, 130.149.21.33:45020: bad datanode 130.149.21.60:45020
23:27:05,292 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1137466152275748739_1203java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:57708 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:05,294 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1137466152275748739_1203 bad datanode[0] 130.149.21.17:45020
23:27:05,294 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1137466152275748739_1203 in pipeline 130.149.21.17:45020, 130.149.21.3:45020: bad datanode 130.149.21.17:45020
23:27:11,357 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2289969600566882656_1225java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:57711 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:11,358 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2289969600566882656_1225 bad datanode[0] 130.149.21.17:45020
23:27:11,359 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2289969600566882656_1225 in pipeline 130.149.21.17:45020, 130.149.21.60:45020: bad datanode 130.149.21.17:45020
23:27:13,349 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8294391577281870958_1237java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:54869 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:13,351 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8294391577281870958_1237 bad datanode[0] 130.149.21.61:45020
23:27:13,351 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8294391577281870958_1237 in pipeline 130.149.21.61:45020, 130.149.21.17:45020: bad datanode 130.149.21.61:45020
23:27:16,019 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_585828411013470731_1248java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:55684 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:16,020 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_585828411013470731_1248 bad datanode[0] 130.149.21.19:45020
23:27:16,021 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_585828411013470731_1248 in pipeline 130.149.21.19:45020, 130.149.21.30:45020: bad datanode 130.149.21.19:45020
23:27:42,622 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2738560298258090871_1278java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.29:32926 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:42,623 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2738560298258090871_1278 bad datanode[0] 130.149.21.3:45020
23:27:42,623 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2738560298258090871_1278 in pipeline 130.149.21.3:45020, 130.149.21.27:45020: bad datanode 130.149.21.3:45020
