23:21:10,825 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:10,862 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:10,872 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:10,882 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-12 to job manager
23:21:10,952 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:10,952 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:10,953 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:12,068 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:12,089 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:12,099 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:12,099 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:47,385 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (7/20)
23:21:47,387 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (7/20)
23:21:50,270 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (52/160)
23:21:50,270 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (52/160)
23:21:50,272 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (52/160)
23:21:50,274 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (52/160)
23:21:50,863 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (54/160)
23:21:50,863 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (54/160)
23:21:50,865 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (54/160)
23:21:50,866 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (54/160)
23:21:51,043 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (55/160)
23:21:51,043 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (55/160)
23:21:51,045 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (55/160)
23:21:51,047 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (55/160)
23:21:51,583 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (51/160)
23:21:51,583 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (51/160)
23:21:51,585 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (51/160)
23:21:51,586 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (51/160)
23:21:52,234 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (56/160)
23:21:52,234 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (56/160)
23:21:52,236 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (56/160)
23:21:52,237 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (56/160)
23:21:52,533 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (53/160)
23:21:52,533 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (53/160)
23:21:52,535 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (53/160)
23:21:52,536 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (53/160)
23:21:52,839 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (49/160)
23:21:52,840 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (49/160)
23:21:52,841 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (49/160)
23:21:52,843 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (49/160)
23:21:53,241 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (50/160)
23:21:53,241 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (50/160)
23:21:53,243 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (50/160)
23:21:53,244 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (50/160)
23:22:32,624 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (7/20)
23:22:32,625 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (7/20)
23:25:55,092 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6006386974034158066_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:51161 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:55,093 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6006386974034158066_1161 bad datanode[0] 130.149.21.16:45020
23:25:55,094 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6006386974034158066_1161 in pipeline 130.149.21.16:45020, 130.149.21.28:45020, 130.149.21.24:45020: bad datanode 130.149.21.16:45020
23:25:56,763 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7621359571591811037_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:51169 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:56,764 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7621359571591811037_1161 bad datanode[0] 130.149.21.16:45020
23:25:56,765 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7621359571591811037_1161 in pipeline 130.149.21.16:45020, 130.149.21.22:45020, 130.149.21.19:45020: bad datanode 130.149.21.16:45020
23:25:57,307 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3164190810021485807_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:51167 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:57,308 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3164190810021485807_1161 bad datanode[0] 130.149.21.16:45020
23:25:57,308 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3164190810021485807_1161 in pipeline 130.149.21.16:45020, 130.149.21.28:45020, 130.149.21.3:45020: bad datanode 130.149.21.16:45020
23:25:57,831 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7459992279732790009_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:51159 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:57,831 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7459992279732790009_1161 bad datanode[0] 130.149.21.16:45020
23:25:57,832 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7459992279732790009_1161 in pipeline 130.149.21.16:45020, 130.149.21.17:45020, 130.149.21.30:45020: bad datanode 130.149.21.16:45020
23:26:01,850 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-9198297317727160394_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:51156 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:01,851 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-9198297317727160394_1161 bad datanode[0] 130.149.21.16:45020
23:26:01,852 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-9198297317727160394_1161 in pipeline 130.149.21.16:45020, 130.149.21.2:45020, 130.149.21.20:45020: bad datanode 130.149.21.16:45020
23:26:03,296 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5046888267628090570_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:51154 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:03,297 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5046888267628090570_1161 bad datanode[0] 130.149.21.16:45020
23:26:03,297 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5046888267628090570_1161 in pipeline 130.149.21.16:45020, 130.149.21.60:45020, 130.149.21.25:45020: bad datanode 130.149.21.16:45020
23:26:03,423 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7412377812632177951_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:51148 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:03,424 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7412377812632177951_1161 bad datanode[0] 130.149.21.16:45020
23:26:03,424 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7412377812632177951_1161 in pipeline 130.149.21.16:45020, 130.149.21.17:45020, 130.149.21.20:45020: bad datanode 130.149.21.16:45020
23:26:03,736 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4405033711848870756_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:51171 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:03,737 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4405033711848870756_1161 bad datanode[0] 130.149.21.16:45020
23:26:03,738 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4405033711848870756_1161 in pipeline 130.149.21.16:45020, 130.149.21.25:45020, 130.149.21.20:45020: bad datanode 130.149.21.16:45020
23:27:01,202 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6006386974034158066_1169java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:49214 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:01,204 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6006386974034158066_1169 bad datanode[0] 130.149.21.28:45020
23:27:01,204 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6006386974034158066_1169 in pipeline 130.149.21.28:45020, 130.149.21.24:45020: bad datanode 130.149.21.28:45020
23:27:02,871 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7621359571591811037_1178java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:40253 remote=/130.149.21.22:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:02,872 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7621359571591811037_1178 bad datanode[0] 130.149.21.22:45020
23:27:02,873 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7621359571591811037_1178 in pipeline 130.149.21.22:45020, 130.149.21.19:45020: bad datanode 130.149.21.22:45020
23:27:03,406 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3164190810021485807_1183java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:49223 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:03,408 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3164190810021485807_1183 bad datanode[0] 130.149.21.28:45020
23:27:03,408 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3164190810021485807_1183 in pipeline 130.149.21.28:45020, 130.149.21.3:45020: bad datanode 130.149.21.28:45020
23:27:03,934 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7459992279732790009_1189java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:53510 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:03,936 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7459992279732790009_1189 bad datanode[0] 130.149.21.17:45020
23:27:03,936 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7459992279732790009_1189 in pipeline 130.149.21.17:45020, 130.149.21.30:45020: bad datanode 130.149.21.17:45020
23:27:08,059 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-9198297317727160394_1213java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:47415 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:08,060 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-9198297317727160394_1213 bad datanode[0] 130.149.21.2:45020
23:27:08,061 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-9198297317727160394_1213 in pipeline 130.149.21.2:45020, 130.149.21.20:45020: bad datanode 130.149.21.2:45020
23:27:09,398 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5046888267628090570_1217java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:48702 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:09,399 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5046888267628090570_1217 bad datanode[0] 130.149.21.60:45020
23:27:09,400 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5046888267628090570_1217 in pipeline 130.149.21.60:45020, 130.149.21.25:45020: bad datanode 130.149.21.60:45020
23:27:09,527 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7412377812632177951_1218java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:53520 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:09,528 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7412377812632177951_1218 bad datanode[0] 130.149.21.17:45020
23:27:09,529 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7412377812632177951_1218 in pipeline 130.149.21.17:45020, 130.149.21.20:45020: bad datanode 130.149.21.17:45020
23:27:09,838 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4405033711848870756_1220java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.16:54537 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:09,840 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4405033711848870756_1220 bad datanode[0] 130.149.21.25:45020
23:27:09,840 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4405033711848870756_1220 in pipeline 130.149.21.25:45020, 130.149.21.20:45020: bad datanode 130.149.21.25:45020
