23:21:12,538 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:12,575 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:12,584 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:12,592 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-20 to job manager
23:21:12,657 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:12,657 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:12,658 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:13,775 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:13,794 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:13,803 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:13,804 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:48,184 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (16/20)
23:21:48,187 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (16/20)
23:21:49,052 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (126/160)
23:21:49,053 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (126/160)
23:21:49,054 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (126/160)
23:21:49,055 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (126/160)
23:21:49,733 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (121/160)
23:21:49,733 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (121/160)
23:21:49,735 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (121/160)
23:21:49,736 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (121/160)
23:21:50,056 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (122/160)
23:21:50,057 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (122/160)
23:21:50,058 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (122/160)
23:21:50,059 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (122/160)
23:21:51,788 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (128/160)
23:21:51,788 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (128/160)
23:21:51,790 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (128/160)
23:21:51,791 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (128/160)
23:21:52,303 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (124/160)
23:21:52,304 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (124/160)
23:21:52,305 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (124/160)
23:21:52,306 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (124/160)
23:21:52,821 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (125/160)
23:21:52,821 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (125/160)
23:21:52,824 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (125/160)
23:21:52,825 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (125/160)
23:21:53,134 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (127/160)
23:21:53,134 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (127/160)
23:21:53,136 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (127/160)
23:21:53,137 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (127/160)
23:21:53,382 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (123/160)
23:21:53,382 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (123/160)
23:21:53,385 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (123/160)
23:21:53,385 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (123/160)
23:22:29,347 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (16/20)
23:22:29,347 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (16/20)
23:25:54,060 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6329052517931329198_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52002 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:54,060 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6329052517931329198_1161 bad datanode[0] 130.149.21.24:45020
23:25:54,062 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6329052517931329198_1161 in pipeline 130.149.21.24:45020, 130.149.21.60:45020, 130.149.21.3:45020: bad datanode 130.149.21.24:45020
23:25:55,670 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-445644506798318148_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52017 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:55,672 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-445644506798318148_1161 bad datanode[0] 130.149.21.24:45020
23:25:55,672 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-445644506798318148_1161 in pipeline 130.149.21.24:45020, 130.149.21.16:45020, 130.149.21.18:45020: bad datanode 130.149.21.24:45020
23:25:56,508 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5988588013717193347_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52012 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:56,509 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5988588013717193347_1161 bad datanode[0] 130.149.21.24:45020
23:25:56,510 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5988588013717193347_1161 in pipeline 130.149.21.24:45020, 130.149.21.30:45020, 130.149.21.17:45020: bad datanode 130.149.21.24:45020
23:25:58,600 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_9001341012693200427_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52020 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:58,601 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9001341012693200427_1161 bad datanode[0] 130.149.21.24:45020
23:25:58,602 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9001341012693200427_1161 in pipeline 130.149.21.24:45020, 130.149.21.18:45020, 130.149.21.3:45020: bad datanode 130.149.21.24:45020
23:25:59,123 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5051303654542341113_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52010 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:59,124 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5051303654542341113_1161 bad datanode[0] 130.149.21.24:45020
23:25:59,124 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5051303654542341113_1161 in pipeline 130.149.21.24:45020, 130.149.21.61:45020, 130.149.21.30:45020: bad datanode 130.149.21.24:45020
23:26:01,824 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6111730239495043302_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52003 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:01,825 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6111730239495043302_1161 bad datanode[0] 130.149.21.24:45020
23:26:01,826 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6111730239495043302_1161 in pipeline 130.149.21.24:45020, 130.149.21.2:45020, 130.149.21.19:45020: bad datanode 130.149.21.24:45020
23:26:04,323 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_461413623294134781_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52014 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:04,324 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_461413623294134781_1161 bad datanode[0] 130.149.21.24:45020
23:26:04,325 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_461413623294134781_1161 in pipeline 130.149.21.24:45020, 130.149.21.18:45020, 130.149.21.2:45020: bad datanode 130.149.21.24:45020
23:26:09,292 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7530789588084793504_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:52022 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:09,293 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7530789588084793504_1161 bad datanode[0] 130.149.21.24:45020
23:26:09,294 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7530789588084793504_1161 in pipeline 130.149.21.24:45020, 130.149.21.18:45020, 130.149.21.21:45020: bad datanode 130.149.21.24:45020
23:27:00,244 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6329052517931329198_1165java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:50425 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:00,245 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6329052517931329198_1165 bad datanode[0] 130.149.21.60:45020
23:27:00,246 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6329052517931329198_1165 in pipeline 130.149.21.60:45020, 130.149.21.3:45020: bad datanode 130.149.21.60:45020
23:27:01,817 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-445644506798318148_1171java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:51986 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:01,818 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-445644506798318148_1171 bad datanode[0] 130.149.21.16:45020
23:27:01,819 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-445644506798318148_1171 in pipeline 130.149.21.16:45020, 130.149.21.18:45020: bad datanode 130.149.21.16:45020
23:27:02,554 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5988588013717193347_1175java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:44464 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:02,556 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5988588013717193347_1175 bad datanode[0] 130.149.21.30:45020
23:27:02,556 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5988588013717193347_1175 in pipeline 130.149.21.30:45020, 130.149.21.17:45020: bad datanode 130.149.21.30:45020
23:27:04,706 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_9001341012693200427_1197java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:33621 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:04,707 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9001341012693200427_1197 bad datanode[0] 130.149.21.18:45020
23:27:04,708 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_9001341012693200427_1197 in pipeline 130.149.21.18:45020, 130.149.21.3:45020: bad datanode 130.149.21.18:45020
23:27:05,254 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5051303654542341113_1201java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:59561 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:05,256 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5051303654542341113_1201 bad datanode[0] 130.149.21.61:45020
23:27:05,256 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5051303654542341113_1201 in pipeline 130.149.21.61:45020, 130.149.21.30:45020: bad datanode 130.149.21.61:45020
23:27:07,919 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6111730239495043302_1210java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:51026 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:07,920 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6111730239495043302_1210 bad datanode[0] 130.149.21.2:45020
23:27:07,920 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6111730239495043302_1210 in pipeline 130.149.21.2:45020, 130.149.21.19:45020: bad datanode 130.149.21.2:45020
23:27:10,424 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_461413623294134781_1222java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:33627 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:10,425 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_461413623294134781_1222 bad datanode[0] 130.149.21.18:45020
23:27:10,426 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_461413623294134781_1222 in pipeline 130.149.21.18:45020, 130.149.21.2:45020: bad datanode 130.149.21.18:45020
23:27:15,332 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7530789588084793504_1246java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.24:33631 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:15,334 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7530789588084793504_1246 bad datanode[0] 130.149.21.18:45020
23:27:15,334 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7530789588084793504_1246 in pipeline 130.149.21.18:45020, 130.149.21.21:45020: bad datanode 130.149.21.18:45020
