23:21:10,981 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:11,018 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:11,028 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:11,037 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-13 to job manager
23:21:11,103 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:11,103 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:11,104 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:12,190 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:12,209 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:12,218 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:12,219 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:48,170 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (8/20)
23:21:48,174 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (8/20)
23:21:49,008 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (62/160)
23:21:49,008 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (62/160)
23:21:49,011 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (62/160)
23:21:49,012 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (62/160)
23:21:49,596 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (60/160)
23:21:49,596 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (60/160)
23:21:49,598 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (60/160)
23:21:49,599 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (60/160)
23:21:50,072 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (61/160)
23:21:50,072 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (61/160)
23:21:50,074 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (61/160)
23:21:50,076 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (61/160)
23:21:50,099 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (57/160)
23:21:50,099 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (57/160)
23:21:50,101 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (57/160)
23:21:50,102 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (57/160)
23:21:51,143 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (58/160)
23:21:51,143 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (58/160)
23:21:51,145 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (58/160)
23:21:51,146 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (58/160)
23:21:51,445 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (63/160)
23:21:51,446 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (63/160)
23:21:51,447 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (63/160)
23:21:51,448 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (63/160)
23:21:51,745 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (64/160)
23:21:51,745 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (64/160)
23:21:51,748 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (64/160)
23:21:51,749 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (64/160)
23:21:51,783 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (59/160)
23:21:51,783 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (59/160)
23:21:51,785 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (59/160)
23:21:51,786 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (59/160)
23:25:03,401 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (8/20)
23:25:03,402 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (8/20)
23:25:58,661 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_490504899814303613_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:57952 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:58,662 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_490504899814303613_1161 bad datanode[0] 130.149.21.17:45020
23:25:58,663 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_490504899814303613_1161 in pipeline 130.149.21.17:45020, 130.149.21.30:45020, 130.149.21.2:45020: bad datanode 130.149.21.17:45020
23:26:01,913 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_121016465123954486_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:57954 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:01,914 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_121016465123954486_1161 bad datanode[0] 130.149.21.17:45020
23:26:01,914 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_121016465123954486_1161 in pipeline 130.149.21.17:45020, 130.149.21.30:45020, 130.149.21.18:45020: bad datanode 130.149.21.17:45020
23:26:03,285 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8367738368754775938_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:57964 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:03,287 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8367738368754775938_1161 bad datanode[0] 130.149.21.17:45020
23:26:03,287 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8367738368754775938_1161 in pipeline 130.149.21.17:45020, 130.149.21.28:45020, 130.149.21.22:45020: bad datanode 130.149.21.17:45020
23:26:06,367 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1391743508898972927_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:57959 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:06,369 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1391743508898972927_1161 bad datanode[0] 130.149.21.17:45020
23:26:06,369 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1391743508898972927_1161 in pipeline 130.149.21.17:45020, 130.149.21.26:45020, 130.149.21.28:45020: bad datanode 130.149.21.17:45020
23:26:07,230 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1129374143349093632_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:57946 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:07,230 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1129374143349093632_1161 bad datanode[0] 130.149.21.17:45020
23:26:07,231 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1129374143349093632_1161 in pipeline 130.149.21.17:45020, 130.149.21.22:45020, 130.149.21.18:45020: bad datanode 130.149.21.17:45020
23:26:08,931 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6099776242421426026_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:57944 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:08,932 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6099776242421426026_1161 bad datanode[0] 130.149.21.17:45020
23:26:08,933 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6099776242421426026_1161 in pipeline 130.149.21.17:45020, 130.149.21.29:45020, 130.149.21.60:45020: bad datanode 130.149.21.17:45020
23:26:10,485 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_772044025373543243_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:57966 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:10,487 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_772044025373543243_1161 bad datanode[0] 130.149.21.17:45020
23:26:10,487 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_772044025373543243_1161 in pipeline 130.149.21.17:45020, 130.149.21.2:45020, 130.149.21.29:45020: bad datanode 130.149.21.17:45020
23:26:10,682 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4299092079602612275_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:57956 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:10,683 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4299092079602612275_1161 bad datanode[0] 130.149.21.17:45020
23:26:10,684 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4299092079602612275_1161 in pipeline 130.149.21.17:45020, 130.149.21.3:45020, 130.149.21.33:45020: bad datanode 130.149.21.17:45020
23:27:04,804 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_490504899814303613_1199java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58889 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:04,805 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_490504899814303613_1199 bad datanode[0] 130.149.21.30:45020
23:27:04,806 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_490504899814303613_1199 in pipeline 130.149.21.30:45020, 130.149.21.2:45020: bad datanode 130.149.21.30:45020
23:27:08,018 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_121016465123954486_1211java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:58895 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:08,020 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_121016465123954486_1211 bad datanode[0] 130.149.21.30:45020
23:27:08,021 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_121016465123954486_1211 in pipeline 130.149.21.30:45020, 130.149.21.18:45020: bad datanode 130.149.21.30:45020
23:27:09,383 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8367738368754775938_1216java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:33716 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:09,385 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8367738368754775938_1216 bad datanode[0] 130.149.21.28:45020
23:27:09,385 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8367738368754775938_1216 in pipeline 130.149.21.28:45020, 130.149.21.22:45020: bad datanode 130.149.21.28:45020
23:27:12,469 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1391743508898972927_1232java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:43378 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:12,470 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1391743508898972927_1232 bad datanode[0] 130.149.21.26:45020
23:27:12,471 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1391743508898972927_1232 in pipeline 130.149.21.26:45020, 130.149.21.28:45020: bad datanode 130.149.21.26:45020
23:27:13,327 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1129374143349093632_1236java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:53193 remote=/130.149.21.22:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:13,329 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1129374143349093632_1236 bad datanode[0] 130.149.21.22:45020
23:27:13,330 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1129374143349093632_1236 in pipeline 130.149.21.22:45020, 130.149.21.18:45020: bad datanode 130.149.21.22:45020
23:27:15,052 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6099776242421426026_1244java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:34322 remote=/130.149.21.29:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:15,054 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6099776242421426026_1244 bad datanode[0] 130.149.21.29:45020
23:27:15,054 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6099776242421426026_1244 in pipeline 130.149.21.29:45020, 130.149.21.60:45020: bad datanode 130.149.21.29:45020
23:27:16,586 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_772044025373543243_1255java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:48076 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:16,588 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_772044025373543243_1255 bad datanode[0] 130.149.21.2:45020
23:27:16,588 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_772044025373543243_1255 in pipeline 130.149.21.2:45020, 130.149.21.29:45020: bad datanode 130.149.21.2:45020
23:27:16,785 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4299092079602612275_1256java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.17:38571 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:16,786 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4299092079602612275_1256 bad datanode[0] 130.149.21.3:45020
23:27:16,787 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4299092079602612275_1256 in pipeline 130.149.21.3:45020, 130.149.21.33:45020: bad datanode 130.149.21.3:45020
