23:21:13,009 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:13,046 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:13,056 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:13,064 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-22 to job manager
23:21:13,129 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:13,129 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:13,130 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:14,256 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:14,276 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:14,285 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:14,285 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:47,641 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (14/20)
23:21:47,643 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (14/20)
23:21:49,256 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (106/160)
23:21:49,256 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (106/160)
23:21:49,258 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (106/160)
23:21:49,260 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (106/160)
23:21:49,836 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (112/160)
23:21:49,837 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (112/160)
23:21:49,838 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (112/160)
23:21:49,840 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (112/160)
23:21:49,989 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (111/160)
23:21:49,989 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (111/160)
23:21:49,991 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (111/160)
23:21:49,992 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (111/160)
23:21:50,779 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (108/160)
23:21:50,779 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (108/160)
23:21:50,781 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (108/160)
23:21:50,782 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (108/160)
23:21:51,202 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (110/160)
23:21:51,202 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (110/160)
23:21:51,204 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (110/160)
23:21:51,205 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (110/160)
23:21:51,707 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (105/160)
23:21:51,708 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (105/160)
23:21:51,709 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (105/160)
23:21:51,711 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (105/160)
23:21:53,144 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (107/160)
23:21:53,144 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (107/160)
23:21:53,146 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (107/160)
23:21:53,147 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (107/160)
23:21:53,945 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (109/160)
23:21:53,945 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (109/160)
23:21:53,947 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (109/160)
23:21:53,948 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (109/160)
23:25:56,072 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8654775761469349740_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:42710 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:56,073 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8654775761469349740_1161 bad datanode[0] 130.149.21.26:45020
23:25:56,074 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8654775761469349740_1161 in pipeline 130.149.21.26:45020, 130.149.21.22:45020, 130.149.21.16:45020: bad datanode 130.149.21.26:45020
23:25:58,137 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3556909359065023584_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:42716 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:58,138 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3556909359065023584_1161 bad datanode[0] 130.149.21.26:45020
23:25:58,139 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3556909359065023584_1161 in pipeline 130.149.21.26:45020, 130.149.21.3:45020, 130.149.21.28:45020: bad datanode 130.149.21.26:45020
23:26:01,487 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1616119721285964945_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:42714 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:01,488 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1616119721285964945_1161 bad datanode[0] 130.149.21.26:45020
23:26:01,489 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1616119721285964945_1161 in pipeline 130.149.21.26:45020, 130.149.21.18:45020, 130.149.21.28:45020: bad datanode 130.149.21.26:45020
23:26:04,144 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-533963537485236543_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:42720 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:04,145 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-533963537485236543_1161 bad datanode[0] 130.149.21.26:45020
23:26:04,145 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-533963537485236543_1161 in pipeline 130.149.21.26:45020, 130.149.21.22:45020, 130.149.21.30:45020: bad datanode 130.149.21.26:45020
23:26:05,770 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_214550110307780062_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:42704 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:05,771 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_214550110307780062_1161 bad datanode[0] 130.149.21.26:45020
23:26:05,772 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_214550110307780062_1161 in pipeline 130.149.21.26:45020, 130.149.21.25:45020, 130.149.21.18:45020: bad datanode 130.149.21.26:45020
23:26:05,835 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4724450182379766539_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:42723 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:05,836 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4724450182379766539_1161 bad datanode[0] 130.149.21.26:45020
23:26:05,837 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4724450182379766539_1161 in pipeline 130.149.21.26:45020, 130.149.21.33:45020, 130.149.21.17:45020: bad datanode 130.149.21.26:45020
23:26:10,349 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8846964419155537754_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:42718 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:10,350 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8846964419155537754_1161 bad datanode[0] 130.149.21.26:45020
23:26:10,351 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8846964419155537754_1161 in pipeline 130.149.21.26:45020, 130.149.21.21:45020, 130.149.21.30:45020: bad datanode 130.149.21.26:45020
23:26:12,563 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6350626905457733736_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:42725 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:12,565 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6350626905457733736_1161 bad datanode[0] 130.149.21.26:45020
23:26:12,565 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6350626905457733736_1161 in pipeline 130.149.21.26:45020, 130.149.21.24:45020, 130.149.21.25:45020: bad datanode 130.149.21.26:45020
23:27:02,208 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_8654775761469349740_1173java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43440 remote=/130.149.21.22:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:02,209 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8654775761469349740_1173 bad datanode[0] 130.149.21.22:45020
23:27:02,210 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_8654775761469349740_1173 in pipeline 130.149.21.22:45020, 130.149.21.16:45020: bad datanode 130.149.21.22:45020
23:27:04,239 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3556909359065023584_1193java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:58851 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:04,240 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3556909359065023584_1193 bad datanode[0] 130.149.21.3:45020
23:27:04,241 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3556909359065023584_1193 in pipeline 130.149.21.3:45020, 130.149.21.28:45020: bad datanode 130.149.21.3:45020
23:27:07,576 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1616119721285964945_1209java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:38950 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:07,577 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1616119721285964945_1209 bad datanode[0] 130.149.21.18:45020
23:27:07,577 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1616119721285964945_1209 in pipeline 130.149.21.18:45020, 130.149.21.28:45020: bad datanode 130.149.21.18:45020
23:27:10,245 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-533963537485236543_1221java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:43448 remote=/130.149.21.22:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:10,246 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-533963537485236543_1221 bad datanode[0] 130.149.21.22:45020
23:27:10,246 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-533963537485236543_1221 in pipeline 130.149.21.22:45020, 130.149.21.30:45020: bad datanode 130.149.21.22:45020
23:27:11,878 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_214550110307780062_1227java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:34156 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:11,879 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_214550110307780062_1227 bad datanode[0] 130.149.21.25:45020
23:27:11,880 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_214550110307780062_1227 in pipeline 130.149.21.25:45020, 130.149.21.18:45020: bad datanode 130.149.21.25:45020
23:27:12,007 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_4724450182379766539_1228java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:45347 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:12,008 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4724450182379766539_1228 bad datanode[0] 130.149.21.33:45020
23:27:12,009 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_4724450182379766539_1228 in pipeline 130.149.21.33:45020, 130.149.21.17:45020: bad datanode 130.149.21.33:45020
23:27:16,393 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-8846964419155537754_1252java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:53853 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:16,394 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8846964419155537754_1252 bad datanode[0] 130.149.21.21:45020
23:27:16,395 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-8846964419155537754_1252 in pipeline 130.149.21.21:45020, 130.149.21.30:45020: bad datanode 130.149.21.21:45020
23:27:18,668 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-6350626905457733736_1263java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.26:40419 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:18,669 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6350626905457733736_1263 bad datanode[0] 130.149.21.24:45020
23:27:18,670 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-6350626905457733736_1263 in pipeline 130.149.21.24:45020, 130.149.21.25:45020: bad datanode 130.149.21.24:45020
