23:21:14,992 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:15,029 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:15,039 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:15,047 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-31 to job manager
23:21:15,111 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:15,111 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:15,112 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:16,226 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:16,245 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:16,254 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:16,255 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:48,184 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (18/20)
23:21:48,186 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (18/20)
23:21:49,680 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (137/160)
23:21:49,680 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (137/160)
23:21:49,682 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (137/160)
23:21:49,684 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (137/160)
23:21:50,259 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (143/160)
23:21:50,259 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (143/160)
23:21:50,261 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (143/160)
23:21:50,262 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (143/160)
23:21:50,552 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (139/160)
23:21:50,552 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (139/160)
23:21:50,554 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (139/160)
23:21:50,555 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (139/160)
23:21:50,855 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (141/160)
23:21:50,856 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (141/160)
23:21:50,857 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (141/160)
23:21:50,858 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (141/160)
23:21:51,152 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (138/160)
23:21:51,152 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (138/160)
23:21:51,154 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (138/160)
23:21:51,155 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (138/160)
23:21:51,793 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (144/160)
23:21:51,793 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (144/160)
23:21:51,795 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (144/160)
23:21:51,797 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (144/160)
23:21:53,581 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (142/160)
23:21:53,581 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (142/160)
23:21:53,584 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (142/160)
23:21:53,586 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (142/160)
23:21:53,889 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (140/160)
23:21:53,889 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (140/160)
23:21:53,890 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (140/160)
23:21:53,892 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (140/160)
23:22:35,715 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (18/20)
23:22:35,716 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (18/20)
23:26:17,581 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_692224126251010585_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:33880 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:17,581 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7387229942614516212_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:33891 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:17,582 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_692224126251010585_1161 bad datanode[0] 130.149.21.33:45020
23:26:17,582 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7387229942614516212_1161 bad datanode[0] 130.149.21.33:45020
23:26:17,583 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_692224126251010585_1161 in pipeline 130.149.21.33:45020, 130.149.21.27:45020, 130.149.21.30:45020: bad datanode 130.149.21.33:45020
23:26:17,584 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7387229942614516212_1161 in pipeline 130.149.21.33:45020, 130.149.21.61:45020, 130.149.21.26:45020: bad datanode 130.149.21.33:45020
23:26:18,583 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7495583985556547406_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:33886 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:18,583 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5874496836688923546_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:33879 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:18,583 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7495583985556547406_1161 bad datanode[0] 130.149.21.33:45020
23:26:18,584 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5874496836688923546_1161 bad datanode[0] 130.149.21.33:45020
23:26:18,584 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7495583985556547406_1161 in pipeline 130.149.21.33:45020, 130.149.21.16:45020, 130.149.21.26:45020: bad datanode 130.149.21.33:45020
23:26:18,585 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5874496836688923546_1161 in pipeline 130.149.21.33:45020, 130.149.21.27:45020, 130.149.21.24:45020: bad datanode 130.149.21.33:45020
23:26:18,659 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6359793065142563713_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:33898 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:18,660 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6359793065142563713_1161 bad datanode[0] 130.149.21.33:45020
23:26:18,660 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6359793065142563713_1161 in pipeline 130.149.21.33:45020, 130.149.21.26:45020, 130.149.21.17:45020: bad datanode 130.149.21.33:45020
23:26:18,663 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7132868548686416186_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:33889 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:18,664 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7132868548686416186_1161 bad datanode[0] 130.149.21.33:45020
23:26:18,664 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7132868548686416186_1161 in pipeline 130.149.21.33:45020, 130.149.21.24:45020, 130.149.21.23:45020: bad datanode 130.149.21.33:45020
23:26:19,702 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1889015835674064834_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:33881 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:19,703 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1889015835674064834_1161 bad datanode[0] 130.149.21.33:45020
23:26:19,703 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1889015835674064834_1161 in pipeline 130.149.21.33:45020, 130.149.21.2:45020, 130.149.21.60:45020: bad datanode 130.149.21.33:45020
23:27:19,767 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4058918346894504032_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:33903 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:19,769 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4058918346894504032_1161 bad datanode[0] 130.149.21.33:45020
23:27:19,769 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4058918346894504032_1161 in pipeline 130.149.21.33:45020, 130.149.21.23:45020, 130.149.21.19:45020: bad datanode 130.149.21.33:45020
23:27:23,655 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_692224126251010585_1265java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:41009 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:23,656 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_692224126251010585_1265 bad datanode[0] 130.149.21.27:45020
23:27:23,656 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_692224126251010585_1265 in pipeline 130.149.21.27:45020, 130.149.21.30:45020: bad datanode 130.149.21.27:45020
23:27:23,695 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7387229942614516212_1264java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:43955 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:23,697 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7387229942614516212_1264 bad datanode[0] 130.149.21.61:45020
23:27:23,697 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7387229942614516212_1264 in pipeline 130.149.21.61:45020, 130.149.21.26:45020: bad datanode 130.149.21.61:45020
23:27:24,685 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7495583985556547406_1266java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:41778 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:24,686 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_5874496836688923546_1267java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:41013 remote=/130.149.21.27:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:24,686 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7495583985556547406_1266 bad datanode[0] 130.149.21.16:45020
23:27:24,688 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5874496836688923546_1267 bad datanode[0] 130.149.21.27:45020
23:27:24,688 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7495583985556547406_1266 in pipeline 130.149.21.16:45020, 130.149.21.26:45020: bad datanode 130.149.21.16:45020
23:27:24,689 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_5874496836688923546_1267 in pipeline 130.149.21.27:45020, 130.149.21.24:45020: bad datanode 130.149.21.27:45020
23:27:24,763 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7132868548686416186_1268java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:42656 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:24,764 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_6359793065142563713_1269java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:49149 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:24,764 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7132868548686416186_1268 bad datanode[0] 130.149.21.24:45020
23:27:24,765 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6359793065142563713_1269 bad datanode[0] 130.149.21.26:45020
23:27:24,766 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7132868548686416186_1268 in pipeline 130.149.21.24:45020, 130.149.21.23:45020: bad datanode 130.149.21.24:45020
23:27:24,766 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_6359793065142563713_1269 in pipeline 130.149.21.26:45020, 130.149.21.17:45020: bad datanode 130.149.21.26:45020
23:27:25,805 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1889015835674064834_1270java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.33:47749 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:25,806 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1889015835674064834_1270 bad datanode[0] 130.149.21.2:45020
23:27:25,806 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1889015835674064834_1270 in pipeline 130.149.21.2:45020, 130.149.21.60:45020: bad datanode 130.149.21.2:45020
