23:21:12,766 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:12,803 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:12,813 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:12,821 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-21 to job manager
23:21:12,885 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:12,885 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:12,886 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:13,995 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:14,013 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:14,023 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:14,023 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:47,652 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (17/20)
23:21:47,655 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (17/20)
23:21:49,168 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (135/160)
23:21:49,168 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (135/160)
23:21:49,171 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (135/160)
23:21:49,172 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (135/160)
23:21:50,599 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (136/160)
23:21:50,599 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (136/160)
23:21:50,601 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (136/160)
23:21:50,602 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (136/160)
23:21:51,759 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (132/160)
23:21:51,759 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (132/160)
23:21:51,761 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (132/160)
23:21:51,762 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (132/160)
23:21:51,792 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (130/160)
23:21:51,793 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (130/160)
23:21:51,795 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (130/160)
23:21:51,795 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (130/160)
23:21:52,707 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (131/160)
23:21:52,707 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (131/160)
23:21:52,710 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (131/160)
23:21:52,711 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (131/160)
23:21:52,740 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (134/160)
23:21:52,741 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (134/160)
23:21:52,742 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (134/160)
23:21:52,743 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (134/160)
23:21:53,015 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (129/160)
23:21:53,016 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (129/160)
23:21:53,017 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (129/160)
23:21:53,018 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (129/160)
23:21:53,035 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (133/160)
23:21:53,035 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (133/160)
23:21:53,036 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (133/160)
23:21:53,037 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (133/160)
23:22:35,532 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (17/20)
23:22:35,533 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (17/20)
23:26:31,172 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2726247167861011126_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:38782 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:31,173 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2726247167861011126_1161 bad datanode[0] 130.149.21.25:45020
23:26:31,174 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2726247167861011126_1161 in pipeline 130.149.21.25:45020, 130.149.21.3:45020, 130.149.21.28:45020: bad datanode 130.149.21.25:45020
23:26:31,699 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1211535057386971726_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:38779 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:31,700 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1211535057386971726_1161 bad datanode[0] 130.149.21.25:45020
23:26:31,701 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1211535057386971726_1161 in pipeline 130.149.21.25:45020, 130.149.21.33:45020, 130.149.21.60:45020: bad datanode 130.149.21.25:45020
23:26:32,235 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2957291054625692679_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:38767 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:32,236 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2957291054625692679_1161 bad datanode[0] 130.149.21.25:45020
23:26:32,236 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2957291054625692679_1161 in pipeline 130.149.21.25:45020, 130.149.21.26:45020, 130.149.21.21:45020: bad datanode 130.149.21.25:45020
23:26:33,159 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4293694331892612711_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:38773 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:33,161 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4293694331892612711_1161 bad datanode[0] 130.149.21.25:45020
23:26:33,161 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4293694331892612711_1161 in pipeline 130.149.21.25:45020, 130.149.21.61:45020, 130.149.21.60:45020: bad datanode 130.149.21.25:45020
23:26:33,239 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1917335654307850871_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:38777 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:33,240 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1917335654307850871_1161 bad datanode[0] 130.149.21.25:45020
23:26:33,240 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1917335654307850871_1161 in pipeline 130.149.21.25:45020, 130.149.21.60:45020, 130.149.21.3:45020: bad datanode 130.149.21.25:45020
23:26:33,720 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7865350242725207454_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:38775 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:33,721 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7865350242725207454_1161 bad datanode[0] 130.149.21.25:45020
23:26:33,722 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7865350242725207454_1161 in pipeline 130.149.21.25:45020, 130.149.21.18:45020, 130.149.21.17:45020: bad datanode 130.149.21.25:45020
23:26:35,248 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3220737577882642003_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:38770 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:35,249 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3220737577882642003_1161 bad datanode[0] 130.149.21.25:45020
23:26:35,250 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3220737577882642003_1161 in pipeline 130.149.21.25:45020, 130.149.21.24:45020, 130.149.21.23:45020: bad datanode 130.149.21.25:45020
23:27:34,240 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3371365276467630633_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:38785 remote=/130.149.21.25:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:34,241 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3371365276467630633_1161 bad datanode[0] 130.149.21.25:45020
23:27:34,242 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3371365276467630633_1161 in pipeline 130.149.21.25:45020, 130.149.21.2:45020, 130.149.21.30:45020: bad datanode 130.149.21.25:45020
23:27:37,756 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1211535057386971726_1272java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:48720 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:37,757 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1211535057386971726_1272 bad datanode[0] 130.149.21.33:45020
23:27:37,757 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1211535057386971726_1272 in pipeline 130.149.21.33:45020, 130.149.21.60:45020: bad datanode 130.149.21.33:45020
23:27:38,339 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2957291054625692679_1273java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:32861 remote=/130.149.21.26:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:38,340 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2957291054625692679_1273 bad datanode[0] 130.149.21.26:45020
23:27:38,341 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2957291054625692679_1273 in pipeline 130.149.21.26:45020, 130.149.21.21:45020: bad datanode 130.149.21.26:45020
23:27:39,262 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4293694331892612711_1274java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:49260 remote=/130.149.21.61:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:39,263 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4293694331892612711_1274 bad datanode[0] 130.149.21.61:45020
23:27:39,264 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4293694331892612711_1274 in pipeline 130.149.21.61:45020, 130.149.21.60:45020: bad datanode 130.149.21.61:45020
23:27:39,343 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-1917335654307850871_1275java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:44434 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:39,344 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1917335654307850871_1275 bad datanode[0] 130.149.21.60:45020
23:27:39,344 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-1917335654307850871_1275 in pipeline 130.149.21.60:45020, 130.149.21.3:45020: bad datanode 130.149.21.60:45020
23:27:39,825 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7865350242725207454_1276java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:35956 remote=/130.149.21.18:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:39,826 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7865350242725207454_1276 bad datanode[0] 130.149.21.18:45020
23:27:39,827 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7865350242725207454_1276 in pipeline 130.149.21.18:45020, 130.149.21.17:45020: bad datanode 130.149.21.18:45020
23:27:41,351 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3220737577882642003_1277java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.25:47483 remote=/130.149.21.24:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:41,352 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3220737577882642003_1277 bad datanode[0] 130.149.21.24:45020
23:27:41,353 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3220737577882642003_1277 in pipeline 130.149.21.24:45020, 130.149.21.23:45020: bad datanode 130.149.21.24:45020
