23:21:14,748 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:14,784 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:14,794 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:14,802 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-30 to job manager
23:21:14,867 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:14,867 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:14,868 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:15,978 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:15,997 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:16,007 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:16,007 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:47,071 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (20/20)
23:21:47,075 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (20/20)
23:21:49,209 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (160/160)
23:21:49,209 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (160/160)
23:21:49,211 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (160/160)
23:21:49,213 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (160/160)
23:21:49,816 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (158/160)
23:21:49,817 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (158/160)
23:21:49,818 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (158/160)
23:21:49,820 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (158/160)
23:21:50,226 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (159/160)
23:21:50,227 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (159/160)
23:21:50,228 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (159/160)
23:21:50,229 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (159/160)
23:21:51,599 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (157/160)
23:21:51,599 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (157/160)
23:21:51,601 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (157/160)
23:21:51,602 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (157/160)
23:21:51,645 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (155/160)
23:21:51,645 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (155/160)
23:21:51,647 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (155/160)
23:21:51,648 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (155/160)
23:21:52,076 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (156/160)
23:21:52,077 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (156/160)
23:21:52,077 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (156/160)
23:21:52,079 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (156/160)
23:21:52,531 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (154/160)
23:21:52,531 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (154/160)
23:21:52,533 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (154/160)
23:21:52,534 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (154/160)
23:21:53,770 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (153/160)
23:21:53,771 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (153/160)
23:21:53,772 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (153/160)
23:21:53,773 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (153/160)
23:22:44,435 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (20/20)
23:22:44,435 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (20/20)
23:25:54,029 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5090919936642146292_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38622 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:54,030 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5090919936642146292_1161 bad datanode[0] 130.149.21.2:45020
23:25:54,031 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5090919936642146292_1161 in pipeline 130.149.21.2:45020, 130.149.21.28:45020, 130.149.21.18:45020: bad datanode 130.149.21.2:45020
23:25:55,668 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4419363026335606353_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38628 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:55,669 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4419363026335606353_1161 bad datanode[0] 130.149.21.2:45020
23:25:55,670 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4419363026335606353_1161 in pipeline 130.149.21.2:45020, 130.149.21.17:45020, 130.149.21.21:45020: bad datanode 130.149.21.2:45020
23:25:56,298 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1934255874226201165_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38633 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:56,299 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1934255874226201165_1161 bad datanode[0] 130.149.21.2:45020
23:25:56,299 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1934255874226201165_1161 in pipeline 130.149.21.2:45020, 130.149.21.17:45020, 130.149.21.24:45020: bad datanode 130.149.21.2:45020
23:26:06,602 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7610778323858685806_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38631 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:06,603 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7610778323858685806_1161 bad datanode[0] 130.149.21.2:45020
23:26:06,603 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7610778323858685806_1161 in pipeline 130.149.21.2:45020, 130.149.21.30:45020, 130.149.21.33:45020: bad datanode 130.149.21.2:45020
23:26:07,052 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2137772698697466971_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38635 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:07,053 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2137772698697466971_1161 bad datanode[0] 130.149.21.2:45020
23:26:07,053 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2137772698697466971_1161 in pipeline 130.149.21.2:45020, 130.149.21.60:45020, 130.149.21.17:45020: bad datanode 130.149.21.2:45020
23:26:08,327 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7428813906587654124_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38624 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:08,328 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7428813906587654124_1161 bad datanode[0] 130.149.21.2:45020
23:26:08,329 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7428813906587654124_1161 in pipeline 130.149.21.2:45020, 130.149.21.28:45020, 130.149.21.20:45020: bad datanode 130.149.21.2:45020
23:26:10,714 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2166747195336180589_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38620 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:10,715 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2166747195336180589_1161 bad datanode[0] 130.149.21.2:45020
23:26:10,716 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2166747195336180589_1161 in pipeline 130.149.21.2:45020, 130.149.21.19:45020, 130.149.21.22:45020: bad datanode 130.149.21.2:45020
23:26:11,425 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3500222428869295001_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:38616 remote=/130.149.21.2:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:11,426 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3500222428869295001_1161 bad datanode[0] 130.149.21.2:45020
23:26:11,427 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3500222428869295001_1161 in pipeline 130.149.21.2:45020, 130.149.21.30:45020, 130.149.21.22:45020: bad datanode 130.149.21.2:45020
23:27:00,204 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-5090919936642146292_1164java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:35461 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:00,205 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5090919936642146292_1164 bad datanode[0] 130.149.21.28:45020
23:27:00,206 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-5090919936642146292_1164 in pipeline 130.149.21.28:45020, 130.149.21.18:45020: bad datanode 130.149.21.28:45020
23:27:01,774 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4419363026335606353_1170java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:49971 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:01,775 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4419363026335606353_1170 bad datanode[0] 130.149.21.17:45020
23:27:01,776 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4419363026335606353_1170 in pipeline 130.149.21.17:45020, 130.149.21.21:45020: bad datanode 130.149.21.17:45020
23:27:02,402 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1934255874226201165_1174java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:49973 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:02,403 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1934255874226201165_1174 bad datanode[0] 130.149.21.17:45020
23:27:02,404 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1934255874226201165_1174 in pipeline 130.149.21.17:45020, 130.149.21.24:45020: bad datanode 130.149.21.17:45020
23:27:12,704 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-7610778323858685806_1233java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:34165 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:12,705 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7610778323858685806_1233 bad datanode[0] 130.149.21.30:45020
23:27:12,705 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-7610778323858685806_1233 in pipeline 130.149.21.30:45020, 130.149.21.33:45020: bad datanode 130.149.21.30:45020
23:27:13,151 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_2137772698697466971_1235java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:36719 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:13,152 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2137772698697466971_1235 bad datanode[0] 130.149.21.60:45020
23:27:13,153 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_2137772698697466971_1235 in pipeline 130.149.21.60:45020, 130.149.21.17:45020: bad datanode 130.149.21.60:45020
23:27:14,429 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_7428813906587654124_1241java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:35477 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:14,430 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7428813906587654124_1241 bad datanode[0] 130.149.21.28:45020
23:27:14,431 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_7428813906587654124_1241 in pipeline 130.149.21.28:45020, 130.149.21.20:45020: bad datanode 130.149.21.28:45020
23:27:16,816 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2166747195336180589_1257java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:58781 remote=/130.149.21.19:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:16,817 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2166747195336180589_1257 bad datanode[0] 130.149.21.19:45020
23:27:16,818 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2166747195336180589_1257 in pipeline 130.149.21.19:45020, 130.149.21.22:45020: bad datanode 130.149.21.19:45020
23:27:17,524 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3500222428869295001_1258java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.2:34174 remote=/130.149.21.30:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:17,525 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3500222428869295001_1258 bad datanode[0] 130.149.21.30:45020
23:27:17,526 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3500222428869295001_1258 in pipeline 130.149.21.30:45020, 130.149.21.22:45020: bad datanode 130.149.21.30:45020
