23:21:13,420 WARN  eu.stratosphere.nephele.configuration.GlobalConfiguration     - Cannot load configuration: unknown element plugins
23:21:13,457 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Reading location of job manager from configuration
23:21:13,467 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Determined address of job manager to be cloud-11.dima.tu-berlin.de/130.149.21.15:6002
23:21:13,474 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Announcing connection information cloud-24 to job manager
23:21:13,538 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server Responder: starting
23:21:13,538 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server listener on 6122: starting
23:21:13,539 INFO  eu.stratosphere.nephele.ipc.Server                            - IPC Server handler 0 on 6122: starting
23:21:14,659 INFO  eu.stratosphere.nephele.taskmanager.bufferprovider.GlobalBufferPool  - Initialized global buffer pool with 32768 buffers with a size 32768 bytes each
23:21:14,679 INFO  eu.stratosphere.nephele.taskmanager.bytebuffered.ByteBufferedChannelManager  - Initialized byte buffered channel manager with sender-side spilling disabled
23:21:14,688 INFO  eu.stratosphere.nephele.instance.HardwareDescriptionFactory   - Found Tenured Gen pool (max: 24051843072, used: 0)
23:21:14,688 INFO  eu.stratosphere.nephele.taskmanager.TaskManager               - Initializing memory manager with 22528 megabytes of memory
23:21:47,776 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Build Triads (12/20)
23:21:47,779 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Build Triads (12/20)
23:21:49,524 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (91/160)
23:21:49,524 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (91/160)
23:21:49,527 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (91/160)
23:21:49,528 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (91/160)
23:21:50,157 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (90/160)
23:21:50,158 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (90/160)
23:21:50,160 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (90/160)
23:21:50,161 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (90/160)
23:21:50,239 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (95/160)
23:21:50,240 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (95/160)
23:21:50,242 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (95/160)
23:21:50,243 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (95/160)
23:21:50,684 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (89/160)
23:21:50,684 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (89/160)
23:21:50,686 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (89/160)
23:21:50,687 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (89/160)
23:21:51,021 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (93/160)
23:21:51,021 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (93/160)
23:21:51,022 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (93/160)
23:21:51,023 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (93/160)
23:21:52,245 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (96/160)
23:21:52,246 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (96/160)
23:21:52,248 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (96/160)
23:21:52,249 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (96/160)
23:21:53,034 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (92/160)
23:21:53,034 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (92/160)
23:21:53,036 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (92/160)
23:21:53,037 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (92/160)
23:21:53,349 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Close Triads (94/160)
23:21:53,349 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from STARTING to RUNNING for task Triangles (94/160)
23:21:53,351 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Start PACT code.: Close Triads (94/160)
23:21:53,352 INFO  eu.stratosphere.pact.runtime.task.DataSinkTask                - Start PACT code: Triangles (94/160)
23:22:34,725 INFO  eu.stratosphere.pact.runtime.task.RegularPactTask             - Finished PACT code.: Build Triads (12/20)
23:22:34,725 INFO  eu.stratosphere.nephele.execution.ExecutionStateTransition    - TM: ExecutionState set from RUNNING to FINISHING for task Build Triads (12/20)
23:25:56,577 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1394295158405107111_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46640 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:56,578 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1394295158405107111_1161 bad datanode[0] 130.149.21.28:45020
23:25:56,579 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1394295158405107111_1161 in pipeline 130.149.21.28:45020, 130.149.21.33:45020, 130.149.21.26:45020: bad datanode 130.149.21.28:45020
23:25:57,583 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_596425182911777111_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46644 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:57,584 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_596425182911777111_1161 bad datanode[0] 130.149.21.28:45020
23:25:57,585 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_596425182911777111_1161 in pipeline 130.149.21.28:45020, 130.149.21.21:45020, 130.149.21.60:45020: bad datanode 130.149.21.28:45020
23:25:57,765 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_300192524555460792_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46622 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:57,766 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_300192524555460792_1161 bad datanode[0] 130.149.21.28:45020
23:25:57,767 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_300192524555460792_1161 in pipeline 130.149.21.28:45020, 130.149.21.60:45020, 130.149.21.25:45020: bad datanode 130.149.21.28:45020
23:25:58,471 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4603584502681045804_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46629 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:25:58,472 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4603584502681045804_1161 bad datanode[0] 130.149.21.28:45020
23:25:58,473 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4603584502681045804_1161 in pipeline 130.149.21.28:45020, 130.149.21.16:45020, 130.149.21.21:45020: bad datanode 130.149.21.28:45020
23:26:01,219 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3408160149763122068_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46633 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:01,220 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3408160149763122068_1161 bad datanode[0] 130.149.21.28:45020
23:26:01,221 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3408160149763122068_1161 in pipeline 130.149.21.28:45020, 130.149.21.21:45020, 130.149.21.33:45020: bad datanode 130.149.21.28:45020
23:26:06,053 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3320522987477194858_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46635 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:06,054 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3320522987477194858_1161 bad datanode[0] 130.149.21.28:45020
23:26:06,055 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3320522987477194858_1161 in pipeline 130.149.21.28:45020, 130.149.21.17:45020, 130.149.21.22:45020: bad datanode 130.149.21.28:45020
23:26:10,150 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2325944366282141375_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46621 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:10,151 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2325944366282141375_1161 bad datanode[0] 130.149.21.28:45020
23:26:10,152 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2325944366282141375_1161 in pipeline 130.149.21.28:45020, 130.149.21.16:45020, 130.149.21.27:45020: bad datanode 130.149.21.28:45020
23:26:41,114 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3098324203113458833_1161java.net.SocketTimeoutException: 69000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:46625 remote=/130.149.21.28:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:26:41,114 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3098324203113458833_1161 bad datanode[0] 130.149.21.28:45020
23:26:41,115 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3098324203113458833_1161 in pipeline 130.149.21.28:45020, 130.149.21.3:45020, 130.149.21.23:45020: bad datanode 130.149.21.28:45020
23:27:02,752 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_1394295158405107111_1176java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:44333 remote=/130.149.21.33:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:02,753 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1394295158405107111_1176 bad datanode[0] 130.149.21.33:45020
23:27:02,753 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_1394295158405107111_1176 in pipeline 130.149.21.33:45020, 130.149.21.26:45020: bad datanode 130.149.21.33:45020
23:27:03,689 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_596425182911777111_1184java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:50760 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:03,690 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_596425182911777111_1184 bad datanode[0] 130.149.21.21:45020
23:27:03,690 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_596425182911777111_1184 in pipeline 130.149.21.21:45020, 130.149.21.60:45020: bad datanode 130.149.21.21:45020
23:27:03,941 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_300192524555460792_1191java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:44356 remote=/130.149.21.60:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:03,942 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_300192524555460792_1191 bad datanode[0] 130.149.21.60:45020
23:27:03,943 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_300192524555460792_1191 in pipeline 130.149.21.60:45020, 130.149.21.25:45020: bad datanode 130.149.21.60:45020
23:27:04,575 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-4603584502681045804_1195java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:36729 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:04,576 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4603584502681045804_1195 bad datanode[0] 130.149.21.16:45020
23:27:04,577 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-4603584502681045804_1195 in pipeline 130.149.21.16:45020, 130.149.21.21:45020: bad datanode 130.149.21.16:45020
23:27:07,321 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_3408160149763122068_1208java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:50766 remote=/130.149.21.21:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:07,322 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3408160149763122068_1208 bad datanode[0] 130.149.21.21:45020
23:27:07,323 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_3408160149763122068_1208 in pipeline 130.149.21.21:45020, 130.149.21.33:45020: bad datanode 130.149.21.21:45020
23:27:12,157 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3320522987477194858_1230java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:58215 remote=/130.149.21.17:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:12,158 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3320522987477194858_1230 bad datanode[0] 130.149.21.17:45020
23:27:12,159 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3320522987477194858_1230 in pipeline 130.149.21.17:45020, 130.149.21.22:45020: bad datanode 130.149.21.17:45020
23:27:16,269 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-2325944366282141375_1250java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:36740 remote=/130.149.21.16:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:16,270 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2325944366282141375_1250 bad datanode[0] 130.149.21.16:45020
23:27:16,270 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-2325944366282141375_1250 in pipeline 130.149.21.16:45020, 130.149.21.27:45020: bad datanode 130.149.21.16:45020
23:27:47,211 WARN  org.apache.hadoop.hdfs.DFSClient                              - DFSOutputStream ResponseProcessor exception  for block blk_-3098324203113458833_1279java.net.SocketTimeoutException: 66000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/130.149.21.28:34616 remote=/130.149.21.3:45020]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:155)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:128)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.hadoop.hdfs.protocol.DataTransferProtocol$PipelineAck.readFields(DataTransferProtocol.java:124)
	at org.apache.hadoop.hdfs.DFSClient$DFSOutputStream$ResponseProcessor.run(DFSClient.java:2582)

23:27:47,213 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3098324203113458833_1279 bad datanode[0] 130.149.21.3:45020
23:27:47,213 WARN  org.apache.hadoop.hdfs.DFSClient                              - Error Recovery for block blk_-3098324203113458833_1279 in pipeline 130.149.21.3:45020, 130.149.21.23:45020: bad datanode 130.149.21.3:45020
